// Auto-generated by forge-skill-from-openapi --target=mcp-server --transport=stdio --harden
// API: posthog-hardened-mcp
// Hardened from posthog-mcp — adds: resource limits, 30s timeouts, strict Zod, audit scaffolds
// 13 tools (pre-pruned from posthog-mcp — already the curated allowlist)

import { Server } from '@modelcontextprotocol/sdk/server/index.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import { CallToolRequestSchema, ListToolsRequestSchema } from '@modelcontextprotocol/sdk/types.js';
import { z } from 'zod';

// ── Hardening constants ───────────────────────────────────────────────────────

const MAX_ARGS_BYTES = 64 * 1024;       // 64 KB input cap
const MAX_RESPONSE_BYTES = 1024 * 1024; // 1 MB response cap
const FETCH_TIMEOUT_MS = 30_000;        // 30 s per request

const BASE_URL = (process.env['POSTHOG_HOST'] ?? 'https://us.posthog.com').replace(/\/$/, '');
const PROJECT_ID = process.env['POSTHOG_PROJECT_ID'] ?? '210890';
const ENVIRONMENT_ID = process.env['POSTHOG_ENVIRONMENT_ID'] ?? PROJECT_ID;

function buildUrl(path: string): string {
  return BASE_URL + path
    .replace('{project_id}', encodeURIComponent(PROJECT_ID))
    .replace('{environment_id}', encodeURIComponent(ENVIRONMENT_ID));
}

async function hardenedFetch(url: string, init: RequestInit): Promise<Response> {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), FETCH_TIMEOUT_MS);
  try {
    return await fetch(url, { ...init, signal: controller.signal });
  } finally {
    clearTimeout(timer);
  }
}

function checkArgSize(args: unknown): void {
  const sz = JSON.stringify(args).length;
  if (sz > MAX_ARGS_BYTES) {
    throw new Error(`Input too large: ${sz} bytes (max ${MAX_ARGS_BYTES})`);
  }
}

function truncateResponse(text: string): string {
  if (text.length > MAX_RESPONSE_BYTES) {
    return text.slice(0, MAX_RESPONSE_BYTES) + '\n[RESPONSE TRUNCATED — exceeded 1 MB limit]';
  }
  return text;
}

// ── Zod input schemas (.strict() — unknown keys rejected) ─────────────────────

export const EnvironmentsDashboardsListInputSchema = z.object({
  format: z.string().optional(),
  limit: z.number().int().optional(),
  offset: z.number().int().optional(),
  search: z.string().max(200).optional(),
}).strict();

export const EnvironmentsEventsListInputSchema = z.object({
  after: z.string().optional(),
  before: z.string().optional(),
  distinct_id: z.number().int().optional(),
  event: z.string().optional(),
  format: z.string().optional(),
  include_person: z.boolean().optional(),
  limit: z.number().int().max(1000).optional(),
  offset: z.number().int().max(100_000).optional(),
  person_id: z.number().int().optional(),
  properties: z.array(z.unknown()).optional(),
  select: z.array(z.string()).optional(),
  where: z.array(z.string()).optional(),
}).strict();

export const EnvironmentsInsightsListInputSchema = z.object({
  basic: z.boolean().optional(),
  created_by: z.string().optional(),
  created_date_from: z.string().optional(),
  created_date_to: z.string().optional(),
  dashboards: z.string().optional(),
  date_from: z.string().optional(),
  date_to: z.string().optional(),
  favorited: z.boolean().optional(),
  format: z.string().optional(),
  insight: z.string().optional(),
  last_viewed_date_from: z.string().optional(),
  last_viewed_date_to: z.string().optional(),
  limit: z.number().int().optional(),
  offset: z.number().int().optional(),
  refresh: z.string().optional(),
  saved: z.boolean().optional(),
  search: z.string().optional(),
  short_id: z.string().optional(),
  tags: z.string().optional(),
  user: z.boolean().optional(),
}).strict();

export const EnvironmentsInsightsCreateInputSchema = z.object({
  format: z.string().optional(),
}).strict();

export const EnvironmentsPersonsListInputSchema = z.object({
  distinct_id: z.string().optional(),
  email: z.string().email().optional(),
  format: z.string().optional(),
  limit: z.number().int().optional(),
  offset: z.number().int().optional(),
  properties: z.array(z.unknown()).optional(),
  search: z.string().optional(),
}).strict();

export const EnvironmentsQueryCreateInputSchema = z.object({
  query: z.record(z.unknown()).optional(),
}).strict();

export const CohortsCreateInputSchema = z.object({
  name: z.string().optional(),
  description: z.string().optional(),
  filters: z.record(z.unknown()).optional(),
  is_static: z.boolean().optional(),
}).strict();

export const ExperimentsListInputSchema = z.object({
  archived: z.boolean().optional(),
  created_by_id: z.number().int().optional(),
  feature_flag_id: z.number().int().optional(),
  limit: z.number().int().optional(),
  offset: z.number().int().optional(),
  order: z.string().optional(),
  prompt_name: z.string().optional(),
  search: z.string().optional(),
  status: z.string().optional(),
}).strict();

export const ExperimentsCreateInputSchema = z.object({
  name: z.string().optional(),
  description: z.string().optional(),
  feature_flag_key: z.string().optional(),
  parameters: z.record(z.unknown()).optional(),
  filters: z.record(z.unknown()).optional(),
  start_date: z.string().optional(),
  end_date: z.string().optional(),
}).strict();

export const FeatureFlagsListInputSchema = z.object({
  active: z.string().optional(),
  created_by_id: z.string().optional(),
  evaluation_runtime: z.string().optional(),
  excluded_properties: z.string().optional(),
  has_evaluation_contexts: z.string().optional(),
  limit: z.number().int().optional(),
  offset: z.number().int().optional(),
  search: z.string().optional(),
  tags: z.string().optional(),
  type: z.string().optional(),
}).strict();

export const FeatureFlagsCreateInputSchema = z.object({
  key: z.string().optional(),
  name: z.string().optional(),
  filters: z.record(z.unknown()).optional(),
  active: z.boolean().optional(),
  rollout_percentage: z.number().min(0).max(100).optional(),
  deleted: z.boolean().optional(),
}).strict();

export const FeatureFlagsRetrieveInputSchema = z.object({
  id: z.number().int(),
}).strict();

export const FeatureFlagsUpdateInputSchema = z.object({
  id: z.number().int(),
  key: z.string().optional(),
  name: z.string().optional(),
  filters: z.record(z.unknown()).optional(),
  active: z.boolean().optional(),
  rollout_percentage: z.number().min(0).max(100).optional(),
  deleted: z.boolean().optional(),
}).strict();

// ── Server init ──────────────────────────────────────────────────────────────

const server = new Server(
  { name: 'posthog-hardened-mcp', version: '1.0.0' },
  { capabilities: { tools: {} } },
);

// ── ListTools ─────────────────────────────────────────────────────────────────

server.setRequestHandler(ListToolsRequestSchema, async () => ({
  tools: [
    {
      "name": "environments_dashboards_list",
      "description": "GET /api/environments/{environment_id}/dashboards/ — list dashboards with optional fuzzy search.",
      inputSchema: {
        type: 'object',
        properties: {
          format: { type: 'string', description: 'Response format.' },
          limit: { type: 'integer', description: 'Number of results per page.' },
          offset: { type: 'integer', description: 'Initial index.' },
          search: { type: 'string', description: 'Fuzzy match against name and description (max 200 chars).' },
        },
      },
    },
    {
      "name": "environments_events_list",
      "description": "GET /api/environments/{environment_id}/events/ — list events (legacy; prefer query for aggregations).",
      inputSchema: {
        type: 'object',
        properties: {
          after: { type: 'string', description: 'Only events after this timestamp.' },
          before: { type: 'string', description: 'Only events before this timestamp.' },
          distinct_id: { type: 'integer', description: 'Filter by distinct id.' },
          event: { type: 'string', description: 'Filter by event name, e.g. $pageview.' },
          format: { type: 'string' },
          include_person: { type: 'boolean', description: 'Include person details.' },
          limit: { type: 'integer', description: 'Max results (max 1000).' },
          offset: { type: 'integer', description: 'Offset (max 100000).' },
          person_id: { type: 'integer' },
          properties: { type: 'array', description: 'Property filters.' },
          select: { type: 'array', description: 'HogQL expressions to return.' },
          where: { type: 'array', description: 'HogQL where expressions.' },
        },
      },
    },
    {
      "name": "environments_insights_list",
      "description": "GET /api/environments/{environment_id}/insights/ — list insights.",
      inputSchema: {
        type: 'object',
        properties: {
          basic: { type: 'boolean' },
          created_by: { type: 'string' },
          created_date_from: { type: 'string' },
          created_date_to: { type: 'string' },
          dashboards: { type: 'string' },
          date_from: { type: 'string' },
          date_to: { type: 'string' },
          favorited: { type: 'boolean' },
          format: { type: 'string' },
          insight: { type: 'string' },
          last_viewed_date_from: { type: 'string' },
          last_viewed_date_to: { type: 'string' },
          limit: { type: 'integer' },
          offset: { type: 'integer' },
          refresh: { type: 'string' },
          saved: { type: 'boolean' },
          search: { type: 'string' },
          short_id: { type: 'string' },
          tags: { type: 'string' },
          user: { type: 'boolean' },
        },
      },
    },
    {
      "name": "environments_insights_create",
      "description": "POST /api/environments/{environment_id}/insights/ — create a new insight.",
      inputSchema: {
        type: 'object',
        properties: {
          format: { type: 'string' },
        },
      },
    },
    {
      "name": "environments_persons_list",
      "description": "GET /api/environments/{environment_id}/persons/ — list persons.",
      inputSchema: {
        type: 'object',
        properties: {
          distinct_id: { type: 'string' },
          email: { type: 'string', description: 'Filter by email (exact match).' },
          format: { type: 'string' },
          limit: { type: 'integer' },
          offset: { type: 'integer' },
          properties: { type: 'array' },
          search: { type: 'string' },
        },
      },
    },
    {
      "name": "environments_query_create",
      "description": "POST /api/environments/{environment_id}/query/ — run a HogQL or other query.",
      inputSchema: {
        type: 'object',
        properties: {
          query: { type: 'object', description: 'Query object per PostHog query schema.' },
        },
      },
    },
    {
      "name": "cohorts_create",
      "description": "POST /api/projects/{project_id}/cohorts/ — create a cohort.",
      inputSchema: {
        type: 'object',
        properties: {
          name: { type: 'string' },
          description: { type: 'string' },
          filters: { type: 'object' },
          is_static: { type: 'boolean' },
        },
      },
    },
    {
      "name": "experiments_list",
      "description": "GET /api/projects/{project_id}/experiments/ — list experiments.",
      inputSchema: {
        type: 'object',
        properties: {
          archived: { type: 'boolean' },
          created_by_id: { type: 'integer' },
          feature_flag_id: { type: 'integer' },
          limit: { type: 'integer' },
          offset: { type: 'integer' },
          order: { type: 'string' },
          prompt_name: { type: 'string' },
          search: { type: 'string' },
          status: { type: 'string' },
        },
      },
    },
    {
      "name": "experiments_create",
      "description": "POST /api/projects/{project_id}/experiments/ — create an experiment.",
      inputSchema: {
        type: 'object',
        properties: {
          name: { type: 'string' },
          description: { type: 'string' },
          feature_flag_key: { type: 'string' },
          parameters: { type: 'object' },
          filters: { type: 'object' },
          start_date: { type: 'string' },
          end_date: { type: 'string' },
        },
      },
    },
    {
      "name": "feature_flags_list",
      "description": "GET /api/projects/{project_id}/feature_flags/ — list feature flags.",
      inputSchema: {
        type: 'object',
        properties: {
          active: { type: 'string' },
          created_by_id: { type: 'string' },
          evaluation_runtime: { type: 'string' },
          excluded_properties: { type: 'string' },
          has_evaluation_contexts: { type: 'string' },
          limit: { type: 'integer' },
          offset: { type: 'integer' },
          search: { type: 'string' },
          tags: { type: 'string' },
          type: { type: 'string' },
        },
      },
    },
    {
      "name": "feature_flags_create",
      "description": "POST /api/projects/{project_id}/feature_flags/ — create a feature flag.",
      inputSchema: {
        type: 'object',
        properties: {
          key: { type: 'string' },
          name: { type: 'string' },
          filters: { type: 'object' },
          active: { type: 'boolean' },
          rollout_percentage: { type: 'number', description: '0-100' },
          deleted: { type: 'boolean' },
        },
      },
    },
    {
      "name": "feature_flags_retrieve",
      "description": "GET /api/projects/{project_id}/feature_flags/{id}/ — get a feature flag by ID.",
      inputSchema: {
        type: 'object',
        properties: {
          id: { type: 'integer', description: 'Feature flag ID.' },
        },
        required: ['id'],
      },
    },
    {
      "name": "feature_flags_update",
      "description": "PUT /api/projects/{project_id}/feature_flags/{id}/ — update a feature flag.",
      inputSchema: {
        type: 'object',
        properties: {
          id: { type: 'integer', description: 'Feature flag ID.' },
          key: { type: 'string' },
          name: { type: 'string' },
          filters: { type: 'object' },
          active: { type: 'boolean' },
          rollout_percentage: { type: 'number', description: '0-100' },
          deleted: { type: 'boolean' },
        },
        required: ['id'],
      },
    },
  ],
}));

// ── CallTool ──────────────────────────────────────────────────────────────────

server.setRequestHandler(CallToolRequestSchema, async (request) => {
  const rawArgs = request.params.arguments ?? {};
  checkArgSize(rawArgs);

  const apiKey = process.env['API_KEY'] ?? process.env['POSTHOG_API_KEY'] ?? '';
  const authHeader = { Authorization: 'Bearer ' + apiKey, 'Content-Type': 'application/json' };

  async function doFetch(url: string, init: RequestInit) {
    try {
      const res = await hardenedFetch(url, init);
      const text = res.status === 204 ? '{}' : await res.text();
      if (!res.ok) return { isError: true, content: [{ type: 'text' as const, text: truncateResponse(text) }] };
      return { content: [{ type: 'text' as const, text: truncateResponse(text) }] };
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify({ code: 'FETCH_ERROR', message: msg }) }] };
    }
  }

  // ── environments_dashboards_list ─────────────────────────────────────────

  if (request.params.name === 'environments_dashboards_list') {
    const input = EnvironmentsDashboardsListInputSchema.parse(rawArgs);
    let url = buildUrl('/api/environments/{environment_id}/dashboards/');
    const qs = new URLSearchParams();
    if (input.format !== undefined) qs.set('format', String(input.format));
    if (input.limit !== undefined) qs.set('limit', String(input.limit));
    if (input.offset !== undefined) qs.set('offset', String(input.offset));
    if (input.search !== undefined) qs.set('search', String(input.search));
    if (qs.toString()) url += '?' + qs.toString();
    return doFetch(url, { method: 'GET', headers: authHeader });
  }

  // ── environments_events_list ─────────────────────────────────────────────

  if (request.params.name === 'environments_events_list') {
    const input = EnvironmentsEventsListInputSchema.parse(rawArgs);
    let url = buildUrl('/api/environments/{environment_id}/events/');
    const qs = new URLSearchParams();
    if (input.after !== undefined) qs.set('after', String(input.after));
    if (input.before !== undefined) qs.set('before', String(input.before));
    if (input.distinct_id !== undefined) qs.set('distinct_id', String(input.distinct_id));
    if (input.event !== undefined) qs.set('event', String(input.event));
    if (input.format !== undefined) qs.set('format', String(input.format));
    if (input.include_person !== undefined) qs.set('include_person', String(input.include_person));
    if (input.limit !== undefined) qs.set('limit', String(input.limit));
    if (input.offset !== undefined) qs.set('offset', String(input.offset));
    if (input.person_id !== undefined) qs.set('person_id', String(input.person_id));
    if (input.properties !== undefined) qs.set('properties', JSON.stringify(input.properties));
    if (input.select !== undefined) qs.set('select', JSON.stringify(input.select));
    if (input.where !== undefined) qs.set('where', JSON.stringify(input.where));
    if (qs.toString()) url += '?' + qs.toString();
    return doFetch(url, { method: 'GET', headers: authHeader });
  }

  // ── environments_insights_list ───────────────────────────────────────────

  if (request.params.name === 'environments_insights_list') {
    const input = EnvironmentsInsightsListInputSchema.parse(rawArgs);
    let url = buildUrl('/api/environments/{environment_id}/insights/');
    const qs = new URLSearchParams();
    if (input.basic !== undefined) qs.set('basic', String(input.basic));
    if (input.created_by !== undefined) qs.set('created_by', String(input.created_by));
    if (input.created_date_from !== undefined) qs.set('created_date_from', String(input.created_date_from));
    if (input.created_date_to !== undefined) qs.set('created_date_to', String(input.created_date_to));
    if (input.dashboards !== undefined) qs.set('dashboards', String(input.dashboards));
    if (input.date_from !== undefined) qs.set('date_from', String(input.date_from));
    if (input.date_to !== undefined) qs.set('date_to', String(input.date_to));
    if (input.favorited !== undefined) qs.set('favorited', String(input.favorited));
    if (input.format !== undefined) qs.set('format', String(input.format));
    if (input.insight !== undefined) qs.set('insight', String(input.insight));
    if (input.last_viewed_date_from !== undefined) qs.set('last_viewed_date_from', String(input.last_viewed_date_from));
    if (input.last_viewed_date_to !== undefined) qs.set('last_viewed_date_to', String(input.last_viewed_date_to));
    if (input.limit !== undefined) qs.set('limit', String(input.limit));
    if (input.offset !== undefined) qs.set('offset', String(input.offset));
    if (input.refresh !== undefined) qs.set('refresh', String(input.refresh));
    if (input.saved !== undefined) qs.set('saved', String(input.saved));
    if (input.search !== undefined) qs.set('search', String(input.search));
    if (input.short_id !== undefined) qs.set('short_id', String(input.short_id));
    if (input.tags !== undefined) qs.set('tags', String(input.tags));
    if (input.user !== undefined) qs.set('user', String(input.user));
    if (qs.toString()) url += '?' + qs.toString();
    return doFetch(url, { method: 'GET', headers: authHeader });
  }

  // ── environments_insights_create ─────────────────────────────────────────

  if (request.params.name === 'environments_insights_create') {
    const input = EnvironmentsInsightsCreateInputSchema.parse(rawArgs);
    let url = buildUrl('/api/environments/{environment_id}/insights/');
    const qs = new URLSearchParams();
    if (input.format !== undefined) qs.set('format', String(input.format));
    if (qs.toString()) url += '?' + qs.toString();
    const bodyPayload = Object.fromEntries(Object.entries(input).filter(([k]) => k !== 'format'));
    return doFetch(url, { method: 'POST', headers: authHeader, body: JSON.stringify(bodyPayload) });
  }

  // ── environments_persons_list ────────────────────────────────────────────

  if (request.params.name === 'environments_persons_list') {
    const input = EnvironmentsPersonsListInputSchema.parse(rawArgs);
    let url = buildUrl('/api/environments/{environment_id}/persons/');
    const qs = new URLSearchParams();
    if (input.distinct_id !== undefined) qs.set('distinct_id', String(input.distinct_id));
    if (input.email !== undefined) qs.set('email', String(input.email));
    if (input.format !== undefined) qs.set('format', String(input.format));
    if (input.limit !== undefined) qs.set('limit', String(input.limit));
    if (input.offset !== undefined) qs.set('offset', String(input.offset));
    if (input.properties !== undefined) qs.set('properties', JSON.stringify(input.properties));
    if (input.search !== undefined) qs.set('search', String(input.search));
    if (qs.toString()) url += '?' + qs.toString();
    return doFetch(url, { method: 'GET', headers: authHeader });
  }

  // ── environments_query_create ────────────────────────────────────────────

  if (request.params.name === 'environments_query_create') {
    const input = EnvironmentsQueryCreateInputSchema.parse(rawArgs);
    const url = buildUrl('/api/environments/{environment_id}/query/');
    return doFetch(url, { method: 'POST', headers: authHeader, body: JSON.stringify(input) });
  }

  // ── cohorts_create ───────────────────────────────────────────────────────

  if (request.params.name === 'cohorts_create') {
    const input = CohortsCreateInputSchema.parse(rawArgs);
    const url = buildUrl('/api/projects/{project_id}/cohorts/');
    return doFetch(url, { method: 'POST', headers: authHeader, body: JSON.stringify(input) });
  }

  // ── experiments_list ─────────────────────────────────────────────────────

  if (request.params.name === 'experiments_list') {
    const input = ExperimentsListInputSchema.parse(rawArgs);
    let url = buildUrl('/api/projects/{project_id}/experiments/');
    const qs = new URLSearchParams();
    if (input.archived !== undefined) qs.set('archived', String(input.archived));
    if (input.created_by_id !== undefined) qs.set('created_by_id', String(input.created_by_id));
    if (input.feature_flag_id !== undefined) qs.set('feature_flag_id', String(input.feature_flag_id));
    if (input.limit !== undefined) qs.set('limit', String(input.limit));
    if (input.offset !== undefined) qs.set('offset', String(input.offset));
    if (input.order !== undefined) qs.set('order', String(input.order));
    if (input.prompt_name !== undefined) qs.set('prompt_name', String(input.prompt_name));
    if (input.search !== undefined) qs.set('search', String(input.search));
    if (input.status !== undefined) qs.set('status', String(input.status));
    if (qs.toString()) url += '?' + qs.toString();
    return doFetch(url, { method: 'GET', headers: authHeader });
  }

  // ── experiments_create ───────────────────────────────────────────────────

  if (request.params.name === 'experiments_create') {
    const input = ExperimentsCreateInputSchema.parse(rawArgs);
    const url = buildUrl('/api/projects/{project_id}/experiments/');
    return doFetch(url, { method: 'POST', headers: authHeader, body: JSON.stringify(input) });
  }

  // ── feature_flags_list ───────────────────────────────────────────────────

  if (request.params.name === 'feature_flags_list') {
    const input = FeatureFlagsListInputSchema.parse(rawArgs);
    let url = buildUrl('/api/projects/{project_id}/feature_flags/');
    const qs = new URLSearchParams();
    if (input.active !== undefined) qs.set('active', String(input.active));
    if (input.created_by_id !== undefined) qs.set('created_by_id', String(input.created_by_id));
    if (input.evaluation_runtime !== undefined) qs.set('evaluation_runtime', String(input.evaluation_runtime));
    if (input.excluded_properties !== undefined) qs.set('excluded_properties', String(input.excluded_properties));
    if (input.has_evaluation_contexts !== undefined) qs.set('has_evaluation_contexts', String(input.has_evaluation_contexts));
    if (input.limit !== undefined) qs.set('limit', String(input.limit));
    if (input.offset !== undefined) qs.set('offset', String(input.offset));
    if (input.search !== undefined) qs.set('search', String(input.search));
    if (input.tags !== undefined) qs.set('tags', String(input.tags));
    if (input.type !== undefined) qs.set('type', String(input.type));
    if (qs.toString()) url += '?' + qs.toString();
    return doFetch(url, { method: 'GET', headers: authHeader });
  }

  // ── feature_flags_create ─────────────────────────────────────────────────

  if (request.params.name === 'feature_flags_create') {
    const input = FeatureFlagsCreateInputSchema.parse(rawArgs);
    const url = buildUrl('/api/projects/{project_id}/feature_flags/');
    return doFetch(url, { method: 'POST', headers: authHeader, body: JSON.stringify(input) });
  }

  // ── feature_flags_retrieve ───────────────────────────────────────────────

  if (request.params.name === 'feature_flags_retrieve') {
    const input = FeatureFlagsRetrieveInputSchema.parse(rawArgs);
    const url = buildUrl(`/api/projects/{project_id}/feature_flags/${encodeURIComponent(String(input.id))}/`);
    return doFetch(url, { method: 'GET', headers: authHeader });
  }

  // ── feature_flags_update ─────────────────────────────────────────────────

  if (request.params.name === 'feature_flags_update') {
    const input = FeatureFlagsUpdateInputSchema.parse(rawArgs);
    const url = buildUrl(`/api/projects/{project_id}/feature_flags/${encodeURIComponent(String(input.id))}/`);
    const { id: _id, ...bodyPayload } = input;
    return doFetch(url, { method: 'PUT', headers: authHeader, body: JSON.stringify(bodyPayload) });
  }

  return {
    isError: true,
    content: [{ type: 'text' as const, text: `Unknown tool: ${request.params.name}` }],
  };
});

// ── Boot ─────────────────────────────────────────────────────────────────────

async function main() {
  const transport = new StdioServerTransport();
  await server.connect(transport);
  process.stderr.write('posthog-hardened-mcp MCP server running on stdio\n');
}

main().catch((err) => {
  process.stderr.write(`Fatal: ${err instanceof Error ? err.message : String(err)}\n`);
  process.exit(1);
});
