// src/audit-log.ts
// Auto-generated by forge-skill-from-openapi --harden
// Tool invocation audit logger — writes to D1 binding AUDIT_DB

interface AuditEntry {
  toolName: string;
  scrubbedArgs: unknown;
  status: 'success' | 'error' | 'rate_limited' | 'auth_denied';
  latencyMs: number;
  userId: string;
  errorCode?: string;
  serverName: string;
}

interface AuditEnv {
  AUDIT_DB: D1Database;
}

export async function logToolCall(env: AuditEnv, entry: AuditEntry): Promise<void> {
  const argsJson = JSON.stringify(entry.scrubbedArgs);
  const hashBuf = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(argsJson));
  const argsSha256 = [...new Uint8Array(hashBuf)].map(b => b.toString(16).padStart(2, '0')).join('');

  try {
    await env.AUDIT_DB.prepare(
      `INSERT INTO mcp_tool_calls (tool_name, args_sha256, response_status, latency_ms, user_id, server_name, error_code)
       VALUES (?, ?, ?, ?, ?, ?, ?)`
    ).bind(
      entry.toolName,
      argsSha256,
      entry.status,
      entry.latencyMs,
      entry.userId,
      entry.serverName,
      entry.errorCode ?? null
    ).run();
  } catch {
    // Never let audit log failure break the tool response
  }
}

export function withAuditLog<T>(
  handler: (toolName: string, args: unknown) => Promise<T>,
  env: AuditEnv,
  serverName: string,
  userId: string,
): (toolName: string, args: unknown) => Promise<T> {
  return async (toolName, args) => {
    const start = Date.now();
    try {
      const result = await handler(toolName, args);
      await logToolCall(env, {
        toolName, scrubbedArgs: args, status: 'success',
        latencyMs: Date.now() - start, userId, serverName,
      });
      return result;
    } catch (err) {
      await logToolCall(env, {
        toolName, scrubbedArgs: args, status: 'error',
        latencyMs: Date.now() - start, userId, serverName,
        errorCode: err instanceof Error ? err.name : 'UnknownError',
      });
      throw err;
    }
  };
}
