/**
 * oauth2-pkce-cache.ts — OAuth2 Authorization Code + PKCE flow (user-facing)
 *
 * Implements the OAuth2 `authorization_code` grant with PKCE (RFC 7636) for
 * user-facing browser flows. Distinct from `oauth2-client-credentials-cache.ts`
 * because PKCE is *interactive*: redirect → user consents → callback receives code
 * → exchange for tokens. No client secret required on the public client.
 *
 * Workers-compatible: uses Web Crypto + fetch only — zero Node.js built-ins.
 *
 * Typical flow:
 *   1. Generate PKCE pair: `const { verifier, challenge } = await generatePkceVerifierAndChallenge()`
 *   2. Store `verifier` in `sessionStorage` (client) — NEVER in a cookie.
 *   3. Redirect user to `client.getAuthorizeUrl({ challenge, state })`.
 *   4. On callback: `const tokens = await client.exchangeCodeForToken(code, verifier)`.
 *   5. On 401: `const fresh = await client.refreshToken(tokens.refresh_token)`.
 *
 * @module oauth2-pkce-cache
 *
 * @example
 *   // In the login handler (Worker or edge function)
 *   const client = createAuth0PkceClient({
 *     domain: env.AUTH0_DOMAIN,
 *     clientId: env.AUTH0_CLIENT_ID,
 *     redirectUri: "https://app.example.com/auth/callback",
 *     audience: env.AUTH0_AUDIENCE,
 *   });
 *
 *   // Step 1 — build the authorize URL
 *   const { verifier, challenge } = await generatePkceVerifierAndChallenge();
 *   // persist `verifier` in sessionStorage on the client side before redirect
 *   const url = client.getAuthorizeUrl({ challenge, state: crypto.randomUUID() });
 *   return Response.redirect(url, 302);
 *
 *   // Step 2 — in the /auth/callback handler
 *   const { code } = new URL(request.url).searchParams;
 *   const verifier = getFromSessionStorage("pkce_verifier"); // client passes it back
 *   const tokens = await client.exchangeCodeForToken(code, verifier);
 *   // store tokens.access_token, tokens.refresh_token securely (HttpOnly cookie / KV)
 */

// ---------------------------------------------------------------------------
// Error
// ---------------------------------------------------------------------------

/** Thrown on any PKCE OAuth2 failure (network, token error, invalid response). */
export class Oauth2PkceError extends Error {
  readonly status?: number;
  readonly body?: string;

  constructor(message: string, opts?: { status?: number; body?: string }) {
    super(message);
    this.name = "Oauth2PkceError";
    this.status = opts?.status;
    this.body = opts?.body;
  }
}

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/** Options for {@link createAuth0PkceClient}. */
export interface Auth0PkceClientOptions {
  /** Auth0 domain, e.g. `"my-tenant.us.auth0.com"`. No trailing slash. */
  domain: string;
  /** Auth0 application Client ID (public — safe to expose in browser). */
  clientId: string;
  /** Where Auth0 will redirect after user consents. Must be allow-listed in Auth0. */
  redirectUri: string;
  /**
   * Auth0 API audience, e.g. `"https://api.example.com"`.
   * Required when exchanging for an access token scoped to your API.
   */
  audience?: string;
  /** Space-separated scopes. Defaults to `"openid profile email"`. */
  scope?: string;
}

/** Additional parameters for {@link Auth0PkceClient.getAuthorizeUrl}. */
export interface GetAuthorizeUrlOptions {
  /** PKCE code challenge (S256 hash of the verifier). */
  challenge: string;
  /** Opaque CSRF state token. Verify this on callback. */
  state: string;
  /** Override the default scope for this specific authorization request. */
  scope?: string;
}

/** Successful token response from Auth0. */
export interface PkceTokenResponse {
  access_token: string;
  /** Present when `offline_access` scope was requested. */
  refresh_token?: string;
  id_token?: string;
  token_type: string;
  expires_in: number;
  scope?: string;
}

/** PKCE verifier/challenge pair generated by {@link generatePkceVerifierAndChallenge}. */
export interface PkceVerifierAndChallenge {
  /** Random 43-128 char URL-safe string. Store in sessionStorage; never send to server. */
  verifier: string;
  /** S256 hash of the verifier. Safe to include in the authorize URL. */
  challenge: string;
  /** Always `"S256"`. Included so callers can pass it to the authorize URL without magic strings. */
  method: "S256";
}

/** The client object returned by {@link createAuth0PkceClient}. */
export interface Auth0PkceClient {
  /**
   * Build the Auth0 authorize URL to which the browser should be redirected.
   * Include the `state` param and verify it on callback to prevent CSRF.
   */
  getAuthorizeUrl(opts: GetAuthorizeUrlOptions): string;

  /**
   * Exchange an authorization `code` (received on the callback URL) for tokens.
   * Requires the original `codeVerifier` that generated the challenge.
   *
   * @throws {Oauth2PkceError} on HTTP error or malformed response.
   */
  exchangeCodeForToken(code: string, codeVerifier: string): Promise<PkceTokenResponse>;

  /**
   * Use a `refresh_token` to obtain a fresh `access_token`.
   * Requires the `offline_access` scope to have been granted.
   *
   * @throws {Oauth2PkceError} on HTTP error or missing refresh_token.
   */
  refreshToken(refreshToken: string): Promise<PkceTokenResponse>;
}

// ---------------------------------------------------------------------------
// PKCE helpers
// ---------------------------------------------------------------------------

/**
 * Generate a cryptographically secure PKCE verifier + S256 challenge pair.
 *
 * Uses Web Crypto (available in CF Workers, browsers, and Node 20+).
 * The verifier is 96 random bytes → 128-char base64url string (well within RFC bounds).
 *
 * @example
 *   const { verifier, challenge, method } = await generatePkceVerifierAndChallenge();
 *   sessionStorage.setItem("pkce_verifier", verifier);
 *   const url = client.getAuthorizeUrl({ challenge, state: crypto.randomUUID() });
 */
export async function generatePkceVerifierAndChallenge(): Promise<PkceVerifierAndChallenge> {
  // 96 random bytes → 128-char base64url verifier (RFC 7636 §4.1: 43-128 chars)
  const randomBytes = new Uint8Array(96);
  crypto.getRandomValues(randomBytes);
  const verifier = base64UrlEncode(randomBytes);

  // S256 = BASE64URL(SHA256(ASCII(verifier)))
  const encoded = new TextEncoder().encode(verifier);
  const digest = await crypto.subtle.digest("SHA-256", encoded);
  const challenge = base64UrlEncode(new Uint8Array(digest));

  return { verifier, challenge, method: "S256" };
}

// ---------------------------------------------------------------------------
// Factory
// ---------------------------------------------------------------------------

/**
 * Create an Auth0 PKCE client scoped to a single tenant + application.
 *
 * The client object is lightweight and stateless — create it per-request in a
 * Worker, or once at module level if domain/clientId never change.
 *
 * @example
 *   const client = createAuth0PkceClient({
 *     domain: "my-tenant.us.auth0.com",
 *     clientId: "abc123",
 *     redirectUri: "https://app.example.com/auth/callback",
 *     audience: "https://api.example.com",
 *   });
 *
 *   // In the login route:
 *   const { verifier, challenge } = await generatePkceVerifierAndChallenge();
 *   const authorizeUrl = client.getAuthorizeUrl({ challenge, state: crypto.randomUUID() });
 *
 *   // In the callback route:
 *   const tokens = await client.exchangeCodeForToken(code, verifier);
 */
export function createAuth0PkceClient(opts: Auth0PkceClientOptions): Auth0PkceClient {
  const {
    domain,
    clientId,
    redirectUri,
    audience,
    scope: defaultScope = "openid profile email",
  } = opts;

  const issuerBase = `https://${domain}`;
  const authorizeEndpoint = `${issuerBase}/authorize`;
  const tokenEndpoint = `${issuerBase}/oauth/token`;

  return {
    getAuthorizeUrl({ challenge, state, scope }: GetAuthorizeUrlOptions): string {
      const params = new URLSearchParams({
        response_type: "code",
        client_id: clientId,
        redirect_uri: redirectUri,
        scope: scope ?? defaultScope,
        state,
        code_challenge: challenge,
        code_challenge_method: "S256",
      });
      if (audience) params.set("audience", audience);
      return `${authorizeEndpoint}?${params.toString()}`;
    },

    async exchangeCodeForToken(
      code: string,
      codeVerifier: string
    ): Promise<PkceTokenResponse> {
      const body: Record<string, string> = {
        grant_type: "authorization_code",
        client_id: clientId,
        code,
        redirect_uri: redirectUri,
        code_verifier: codeVerifier,
      };
      if (audience) body.audience = audience;
      return _postToken(tokenEndpoint, body);
    },

    async refreshToken(refreshToken: string): Promise<PkceTokenResponse> {
      return _postToken(tokenEndpoint, {
        grant_type: "refresh_token",
        client_id: clientId,
        refresh_token: refreshToken,
      });
    },
  };
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

/** POST to a token endpoint with `application/x-www-form-urlencoded` body. */
async function _postToken(
  endpoint: string,
  body: Record<string, string>
): Promise<PkceTokenResponse> {
  let response: Response;
  try {
    response = await fetch(endpoint, {
      method: "POST",
      headers: { "Content-Type": "application/x-www-form-urlencoded" },
      body: new URLSearchParams(body).toString(),
    });
  } catch (err) {
    throw new Oauth2PkceError(`Network error reaching ${endpoint}: ${String(err)}`);
  }

  const text = await response.text();
  if (!response.ok) {
    throw new Oauth2PkceError(
      `Token endpoint returned ${response.status}: ${text.slice(0, 200)}`,
      { status: response.status, body: text }
    );
  }

  let json: unknown;
  try {
    json = JSON.parse(text);
  } catch {
    throw new Oauth2PkceError(`Token endpoint returned non-JSON: ${text.slice(0, 200)}`);
  }

  const tokenResp = json as Record<string, unknown>;
  if (typeof tokenResp.access_token !== "string" || typeof tokenResp.token_type !== "string") {
    throw new Oauth2PkceError(
      `Token response missing required fields: ${JSON.stringify(Object.keys(tokenResp))}`
    );
  }

  return tokenResp as unknown as PkceTokenResponse;
}

/** Encode a Uint8Array to a URL-safe base64 string (no padding). */
function base64UrlEncode(bytes: Uint8Array): string {
  let str = "";
  for (let i = 0; i < bytes.length; i++) {
    str += String.fromCharCode(bytes[i]);
  }
  return btoa(str).replace(/\+/g, "-").replace(/\//g, "_").replace(/=/g, "");
}

// ---------------------------------------------------------------------------
// Vitest test suite (8 cases, co-located per [[tdd-first]])
// ---------------------------------------------------------------------------

if (import.meta.vitest) {
  const { describe, it, expect, vi, beforeEach } = import.meta.vitest;

  describe("generatePkceVerifierAndChallenge", () => {
    it("returns a verifier of length 128 chars (96 bytes base64url)", async () => {
      const { verifier } = await generatePkceVerifierAndChallenge();
      expect(verifier.length).toBe(128);
    });

    it("verifier contains only URL-safe base64 chars", async () => {
      const { verifier } = await generatePkceVerifierAndChallenge();
      expect(verifier).toMatch(/^[A-Za-z0-9\-_]+$/);
    });

    it("challenge is a non-empty string distinct from verifier", async () => {
      const { verifier, challenge } = await generatePkceVerifierAndChallenge();
      expect(typeof challenge).toBe("string");
      expect(challenge.length).toBeGreaterThan(0);
      expect(challenge).not.toBe(verifier);
    });

    it("method is always S256", async () => {
      const { method } = await generatePkceVerifierAndChallenge();
      expect(method).toBe("S256");
    });
  });

  describe("createAuth0PkceClient", () => {
    const client = createAuth0PkceClient({
      domain: "test.us.auth0.com",
      clientId: "test-client-id",
      redirectUri: "https://app.test/callback",
      audience: "https://api.test",
    });

    it("getAuthorizeUrl returns correct base URL with required params", async () => {
      const { challenge } = await generatePkceVerifierAndChallenge();
      const url = client.getAuthorizeUrl({ challenge, state: "state123" });
      expect(url).toMatch(/^https:\/\/test\.us\.auth0\.com\/authorize\?/);
      const params = new URL(url).searchParams;
      expect(params.get("response_type")).toBe("code");
      expect(params.get("client_id")).toBe("test-client-id");
      expect(params.get("code_challenge_method")).toBe("S256");
      expect(params.get("code_challenge")).toBe(challenge);
      expect(params.get("state")).toBe("state123");
      expect(params.get("audience")).toBe("https://api.test");
    });

    it("exchangeCodeForToken posts correct grant_type and code_verifier", async () => {
      const mockResponse = {
        access_token: "tok-abc",
        token_type: "Bearer",
        expires_in: 3600,
      };
      const fetchSpy = vi.spyOn(globalThis, "fetch").mockResolvedValueOnce(
        new Response(JSON.stringify(mockResponse), { status: 200 })
      );

      const tokens = await client.exchangeCodeForToken("auth-code", "verifier-xyz");
      expect(tokens.access_token).toBe("tok-abc");
      const [url, init] = fetchSpy.mock.calls[0] as [string, RequestInit];
      expect(url).toBe("https://test.us.auth0.com/oauth/token");
      const body = new URLSearchParams(init.body as string);
      expect(body.get("grant_type")).toBe("authorization_code");
      expect(body.get("code_verifier")).toBe("verifier-xyz");
      fetchSpy.mockRestore();
    });

    it("refreshToken posts correct grant_type and refresh_token", async () => {
      const mockResponse = {
        access_token: "tok-new",
        token_type: "Bearer",
        expires_in: 3600,
      };
      const fetchSpy = vi.spyOn(globalThis, "fetch").mockResolvedValueOnce(
        new Response(JSON.stringify(mockResponse), { status: 200 })
      );

      const tokens = await client.refreshToken("refresh-xyz");
      expect(tokens.access_token).toBe("tok-new");
      const [, init] = fetchSpy.mock.calls[0] as [string, RequestInit];
      const body = new URLSearchParams(init.body as string);
      expect(body.get("grant_type")).toBe("refresh_token");
      expect(body.get("refresh_token")).toBe("refresh-xyz");
      fetchSpy.mockRestore();
    });

    it("exchangeCodeForToken throws Oauth2PkceError on HTTP 400", async () => {
      vi.spyOn(globalThis, "fetch").mockResolvedValueOnce(
        new Response(JSON.stringify({ error: "invalid_grant" }), { status: 400 })
      );
      await expect(client.exchangeCodeForToken("bad-code", "bad-verifier")).rejects.toThrow(
        Oauth2PkceError
      );
      vi.restoreAllMocks();
    });

    it("exchangeCodeForToken throws Oauth2PkceError on network failure", async () => {
      vi.spyOn(globalThis, "fetch").mockRejectedValueOnce(new TypeError("Failed to fetch"));
      await expect(client.exchangeCodeForToken("any", "any")).rejects.toThrow(Oauth2PkceError);
      vi.restoreAllMocks();
    });

    it("exchangeCodeForToken throws Oauth2PkceError on non-JSON response", async () => {
      vi.spyOn(globalThis, "fetch").mockResolvedValueOnce(
        new Response("not-json", { status: 200 })
      );
      await expect(client.exchangeCodeForToken("c", "v")).rejects.toThrow(Oauth2PkceError);
      vi.restoreAllMocks();
    });
  });
}
