// Auto-generated by forge-skill-from-openapi
// API: {{API_NAME}}
// Source: {{API_TITLE}} v{{API_VERSION}}
// Generated: {{GENERATED_DATE}}
// DO NOT EDIT — re-run forge to regenerate

// ── Schema Types ────────────────────────────────────────────────────────────
{{SCHEMA_TYPES}}

// ── Operation Types ─────────────────────────────────────────────────────────
{{OPERATION_TYPES}}
