// Auto-generated by forge-skill-from-openapi --target=mcp-server --transport=stdio
// API: bitwarden-mcp
// DO NOT EDIT — re-run forge to regenerate

import { Server } from '@modelcontextprotocol/sdk/server/index.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import { CallToolRequestSchema, ListToolsRequestSchema } from '@modelcontextprotocol/sdk/types.js';
import { z } from 'zod';

// ── Zod input schemas (one per operation) ────────────────────────────────────

export const ListItemsInputSchema = z.object({}).strict();

export const GetItemInputSchema = z.object({
  id: z.string().describe("The item's ID"),
}).strict();

export const EditItemInputSchema = z.object({
  id: z.string().describe("The item's ID"),
  body: z.record(z.unknown()).optional(),
}).strict();

export const DeleteItemInputSchema = z.object({
  id: z.string().describe("The item's ID"),
}).strict();

export const CreateItemInputSchema = z.object({
  body: z.record(z.unknown()).optional(),
}).strict();

export const ListOrgCollectionsInputSchema = z.object({}).strict();

export const CreateOrgCollectionInputSchema = z.object({
  body: z.record(z.unknown()).optional(),
}).strict();

export const GetOrgCollectionInputSchema = z.object({
  id: z.string().describe("The collection's ID"),
}).strict();

export const EditOrgCollectionInputSchema = z.object({
  id: z.string().describe("The collection's ID"),
  body: z.record(z.unknown()).optional(),
}).strict();

export const DeleteOrgCollectionInputSchema = z.object({
  id: z.string().describe("The collection's ID"),
}).strict();

export const ListOrgMembersInputSchema = z.object({}).strict();

export const InviteOrgMemberInputSchema = z.object({
  body: z.record(z.unknown()).optional(),
}).strict();

export const GetOrgMemberInputSchema = z.object({
  id: z.string().describe("The member's ID"),
}).strict();

export const UpdateOrgMemberInputSchema = z.object({
  id: z.string().describe("The member's ID"),
  body: z.record(z.unknown()).optional(),
}).strict();

export const RemoveOrgMemberInputSchema = z.object({
  id: z.string().describe("The member's ID"),
}).strict();

export const ReinviteOrgMemberInputSchema = z.object({
  id: z.string().describe("The member's ID"),
}).strict();

export const ConfirmOrgMemberInputSchema = z.object({
  id: z.string().describe("The member's ID"),
  key: z.string().describe("The member's encrypted symmetric key"),
}).strict();

export const ListOrgGroupsInputSchema = z.object({}).strict();

export const CreateOrgGroupInputSchema = z.object({
  body: z.record(z.unknown()).optional(),
}).strict();

export const GetOrgGroupInputSchema = z.object({
  id: z.string().describe("The group's ID"),
}).strict();

export const UpdateOrgGroupInputSchema = z.object({
  id: z.string().describe("The group's ID"),
  body: z.record(z.unknown()).optional(),
}).strict();

export const DeleteOrgGroupInputSchema = z.object({
  id: z.string().describe("The group's ID"),
}).strict();

export const GetOrgGroupMemberIdsInputSchema = z.object({
  id: z.string().describe("The group's ID"),
}).strict();

export const UpdateOrgGroupMembersInputSchema = z.object({
  id: z.string().describe("The group's ID"),
  body: z.record(z.unknown()).optional(),
}).strict();

export const GetOrgEventsInputSchema = z.object({
  start: z.string().describe("Start date for event range").optional(),
  end: z.string().describe("End date for event range").optional(),
  continuationToken: z.string().describe("Continuation token for pagination").optional(),
}).strict();

export const ListOrgPoliciesInputSchema = z.object({}).strict();

export const GetOrgPolicyInputSchema = z.object({
  type: z.number().int().describe("Policy type (0=TwoFactorAuthentication, 1=MasterPassword, etc.)"),
}).strict();

export const UpdateOrgPolicyInputSchema = z.object({
  type: z.number().int().describe("Policy type"),
  body: z.record(z.unknown()).optional(),
}).strict();

// ── Server init ──────────────────────────────────────────────────────────────

const server = new Server(
  { name: "bitwarden-mcp", version: '1.0.0' },
  { capabilities: { tools: {} } },
);

// ── ListTools ─────────────────────────────────────────────────────────────────

server.setRequestHandler(ListToolsRequestSchema, async () => ({
  tools: [
  {
    "name": "list_items",
    "description": "List all items in the organization vault",
    "inputSchema": {
      "type": "object",
      "properties": {}
    }
  },
  {
    "name": "get_item",
    "description": "Retrieve a vault item",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "description": "The item's ID"
        }
      },
      "required": [
        "id"
      ]
    }
  },
  {
    "name": "edit_item",
    "description": "Update a vault item",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "description": "The item's ID"
        }
      },
      "required": [
        "id"
      ]
    }
  },
  /** @dangerous */
  {
    "name": "delete_item",
    "description": "Delete a vault item",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "description": "The item's ID"
        }
      },
      "required": [
        "id"
      ]
    }
  },
  {
    "name": "create_item",
    "description": "Create a new vault item in an existing collection",
    "inputSchema": {
      "type": "object",
      "properties": {}
    }
  },
  {
    "name": "list_org_collections",
    "description": "List all collections in the organization",
    "inputSchema": {
      "type": "object",
      "properties": {}
    }
  },
  {
    "name": "create_org_collection",
    "description": "Create a new collection",
    "inputSchema": {
      "type": "object",
      "properties": {}
    }
  },
  {
    "name": "get_org_collection",
    "description": "Retrieve a collection",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "description": "The collection's ID"
        }
      },
      "required": [
        "id"
      ]
    }
  },
  {
    "name": "edit_org_collection",
    "description": "Update a collection",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "description": "The collection's ID"
        }
      },
      "required": [
        "id"
      ]
    }
  },
  /** @dangerous */
  {
    "name": "delete_org_collection",
    "description": "Delete a collection",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "description": "The collection's ID"
        }
      },
      "required": [
        "id"
      ]
    }
  },
  {
    "name": "list_org_members",
    "description": "List all members of the organization",
    "inputSchema": {
      "type": "object",
      "properties": {}
    }
  },
  {
    "name": "invite_org_member",
    "description": "Invite a new member to the organization",
    "inputSchema": {
      "type": "object",
      "properties": {}
    }
  },
  {
    "name": "get_org_member",
    "description": "Retrieve a member of the organization",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "description": "The member's ID"
        }
      },
      "required": [
        "id"
      ]
    }
  },
  {
    "name": "update_org_member",
    "description": "Update an organization member",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "description": "The member's ID"
        }
      },
      "required": [
        "id"
      ]
    }
  },
  /** @dangerous */
  {
    "name": "remove_org_member",
    "description": "Remove a member from the organization",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "description": "The member's ID"
        }
      },
      "required": [
        "id"
      ]
    }
  },
  {
    "name": "reinvite_org_member",
    "description": "Re-invite a member to the organization",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "description": "The member's ID"
        }
      },
      "required": [
        "id"
      ]
    }
  },
  {
    "name": "confirm_org_member",
    "description": "Confirm a member of the organization",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "description": "The member's ID"
        },
        "key": {
          "type": "string",
          "description": "The member's encrypted symmetric key"
        }
      },
      "required": [
        "id",
        "key"
      ]
    }
  },
  {
    "name": "list_org_groups",
    "description": "List all groups in the organization",
    "inputSchema": {
      "type": "object",
      "properties": {}
    }
  },
  {
    "name": "create_org_group",
    "description": "Create a new group",
    "inputSchema": {
      "type": "object",
      "properties": {}
    }
  },
  {
    "name": "get_org_group",
    "description": "Retrieve a group",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "description": "The group's ID"
        }
      },
      "required": [
        "id"
      ]
    }
  },
  {
    "name": "update_org_group",
    "description": "Update a group",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "description": "The group's ID"
        }
      },
      "required": [
        "id"
      ]
    }
  },
  /** @dangerous */
  {
    "name": "delete_org_group",
    "description": "Delete a group",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "description": "The group's ID"
        }
      },
      "required": [
        "id"
      ]
    }
  },
  {
    "name": "get_org_group_member_ids",
    "description": "Get member IDs for a group",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "description": "The group's ID"
        }
      },
      "required": [
        "id"
      ]
    }
  },
  {
    "name": "update_org_group_members",
    "description": "Update members of a group",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "description": "The group's ID"
        }
      },
      "required": [
        "id"
      ]
    }
  },
  {
    "name": "get_org_events",
    "description": "List organization event logs",
    "inputSchema": {
      "type": "object",
      "properties": {
        "start": {
          "type": "string",
          "description": "Start date for event range"
        },
        "end": {
          "type": "string",
          "description": "End date for event range"
        },
        "continuationToken": {
          "type": "string",
          "description": "Continuation token for pagination"
        }
      }
    }
  },
  {
    "name": "list_org_policies",
    "description": "List all policies for the organization",
    "inputSchema": {
      "type": "object",
      "properties": {}
    }
  },
  {
    "name": "get_org_policy",
    "description": "Retrieve a policy by type",
    "inputSchema": {
      "type": "object",
      "properties": {
        "type": {
          "type": "integer",
          "description": "Policy type (0=TwoFactorAuthentication, 1=MasterPassword, etc.)"
        }
      },
      "required": [
        "type"
      ]
    }
  },
  {
    "name": "update_org_policy",
    "description": "Update a policy",
    "inputSchema": {
      "type": "object",
      "properties": {
        "type": {
          "type": "integer",
          "description": "Policy type"
        }
      },
      "required": [
        "type"
      ]
    }
  }
],
}));

// ── CallTool ──────────────────────────────────────────────────────────────────

server.setRequestHandler(CallToolRequestSchema, async (request) => {
    if (request.params.name === "list_items") {
      const input = ListItemsInputSchema.parse(request.params.arguments ?? {});
      let url = "https://api.bitwarden.com/public/ciphers";
      try {
        const res = await fetch(url, {
          method: "GET",
          headers: {
            'Content-Type': 'application/json',
            'Authorization': 'Bearer ' + (process.env['API_KEY'] ?? ''),
          },
          
        });
        const data = res.status === 204 ? {} : await res.json().catch(() => ({}));
        if (!res.ok) return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
        return { content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
      } catch (err) {
        return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify({ code: 'FETCH_ERROR', message: String(err) }) }] };
      }
    }

    if (request.params.name === "get_item") {
      const input = GetItemInputSchema.parse(request.params.arguments ?? {});
      let url = "https://api.bitwarden.com/public/ciphers/{id}";
      url = url.replace('{id}', encodeURIComponent(String(input.id)));
      try {
        const res = await fetch(url, {
          method: "GET",
          headers: {
            'Content-Type': 'application/json',
            'Authorization': 'Bearer ' + (process.env['API_KEY'] ?? ''),
          },
          
        });
        const data = res.status === 204 ? {} : await res.json().catch(() => ({}));
        if (!res.ok) return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
        return { content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
      } catch (err) {
        return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify({ code: 'FETCH_ERROR', message: String(err) }) }] };
      }
    }

    if (request.params.name === "edit_item") {
      const input = EditItemInputSchema.parse(request.params.arguments ?? {});
      let url = "https://api.bitwarden.com/public/ciphers/{id}";
      url = url.replace('{id}', encodeURIComponent(String(input.id)));
      const bodyKeys = new Set(["id"]);
      const bodyPayload = Object.fromEntries(Object.entries(input).filter(([k]) => !bodyKeys.has(k)));
      try {
        const res = await fetch(url, {
          method: "PUT",
          headers: {
            'Content-Type': 'application/json',
            'Authorization': 'Bearer ' + (process.env['API_KEY'] ?? ''),
          },
          body: JSON.stringify(bodyPayload),
        });
        const data = res.status === 204 ? {} : await res.json().catch(() => ({}));
        if (!res.ok) return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
        return { content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
      } catch (err) {
        return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify({ code: 'FETCH_ERROR', message: String(err) }) }] };
      }
    }

    if (request.params.name === "delete_item") {
      const input = DeleteItemInputSchema.parse(request.params.arguments ?? {});
      let url = "https://api.bitwarden.com/public/ciphers/{id}";
      url = url.replace('{id}', encodeURIComponent(String(input.id)));
      try {
        const res = await fetch(url, {
          method: "DELETE",
          headers: {
            'Content-Type': 'application/json',
            'Authorization': 'Bearer ' + (process.env['API_KEY'] ?? ''),
          },
          
        });
        const data = res.status === 204 ? {} : await res.json().catch(() => ({}));
        if (!res.ok) return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
        return { content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
      } catch (err) {
        return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify({ code: 'FETCH_ERROR', message: String(err) }) }] };
      }
    }

    if (request.params.name === "create_item") {
      const input = CreateItemInputSchema.parse(request.params.arguments ?? {});
      let url = "https://api.bitwarden.com/public/ciphers/create";
      const bodyKeys = new Set([]);
      const bodyPayload = Object.fromEntries(Object.entries(input).filter(([k]) => !bodyKeys.has(k)));
      try {
        const res = await fetch(url, {
          method: "POST",
          headers: {
            'Content-Type': 'application/json',
            'Authorization': 'Bearer ' + (process.env['API_KEY'] ?? ''),
          },
          body: JSON.stringify(bodyPayload),
        });
        const data = res.status === 204 ? {} : await res.json().catch(() => ({}));
        if (!res.ok) return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
        return { content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
      } catch (err) {
        return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify({ code: 'FETCH_ERROR', message: String(err) }) }] };
      }
    }

    if (request.params.name === "list_org_collections") {
      const input = ListOrgCollectionsInputSchema.parse(request.params.arguments ?? {});
      let url = "https://api.bitwarden.com/public/collections";
      try {
        const res = await fetch(url, {
          method: "GET",
          headers: {
            'Content-Type': 'application/json',
            'Authorization': 'Bearer ' + (process.env['API_KEY'] ?? ''),
          },
          
        });
        const data = res.status === 204 ? {} : await res.json().catch(() => ({}));
        if (!res.ok) return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
        return { content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
      } catch (err) {
        return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify({ code: 'FETCH_ERROR', message: String(err) }) }] };
      }
    }

    if (request.params.name === "create_org_collection") {
      const input = CreateOrgCollectionInputSchema.parse(request.params.arguments ?? {});
      let url = "https://api.bitwarden.com/public/collections";
      const bodyKeys = new Set([]);
      const bodyPayload = Object.fromEntries(Object.entries(input).filter(([k]) => !bodyKeys.has(k)));
      try {
        const res = await fetch(url, {
          method: "POST",
          headers: {
            'Content-Type': 'application/json',
            'Authorization': 'Bearer ' + (process.env['API_KEY'] ?? ''),
          },
          body: JSON.stringify(bodyPayload),
        });
        const data = res.status === 204 ? {} : await res.json().catch(() => ({}));
        if (!res.ok) return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
        return { content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
      } catch (err) {
        return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify({ code: 'FETCH_ERROR', message: String(err) }) }] };
      }
    }

    if (request.params.name === "get_org_collection") {
      const input = GetOrgCollectionInputSchema.parse(request.params.arguments ?? {});
      let url = "https://api.bitwarden.com/public/collections/{id}";
      url = url.replace('{id}', encodeURIComponent(String(input.id)));
      try {
        const res = await fetch(url, {
          method: "GET",
          headers: {
            'Content-Type': 'application/json',
            'Authorization': 'Bearer ' + (process.env['API_KEY'] ?? ''),
          },
          
        });
        const data = res.status === 204 ? {} : await res.json().catch(() => ({}));
        if (!res.ok) return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
        return { content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
      } catch (err) {
        return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify({ code: 'FETCH_ERROR', message: String(err) }) }] };
      }
    }

    if (request.params.name === "edit_org_collection") {
      const input = EditOrgCollectionInputSchema.parse(request.params.arguments ?? {});
      let url = "https://api.bitwarden.com/public/collections/{id}";
      url = url.replace('{id}', encodeURIComponent(String(input.id)));
      const bodyKeys = new Set(["id"]);
      const bodyPayload = Object.fromEntries(Object.entries(input).filter(([k]) => !bodyKeys.has(k)));
      try {
        const res = await fetch(url, {
          method: "PUT",
          headers: {
            'Content-Type': 'application/json',
            'Authorization': 'Bearer ' + (process.env['API_KEY'] ?? ''),
          },
          body: JSON.stringify(bodyPayload),
        });
        const data = res.status === 204 ? {} : await res.json().catch(() => ({}));
        if (!res.ok) return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
        return { content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
      } catch (err) {
        return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify({ code: 'FETCH_ERROR', message: String(err) }) }] };
      }
    }

    if (request.params.name === "delete_org_collection") {
      const input = DeleteOrgCollectionInputSchema.parse(request.params.arguments ?? {});
      let url = "https://api.bitwarden.com/public/collections/{id}";
      url = url.replace('{id}', encodeURIComponent(String(input.id)));
      try {
        const res = await fetch(url, {
          method: "DELETE",
          headers: {
            'Content-Type': 'application/json',
            'Authorization': 'Bearer ' + (process.env['API_KEY'] ?? ''),
          },
          
        });
        const data = res.status === 204 ? {} : await res.json().catch(() => ({}));
        if (!res.ok) return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
        return { content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
      } catch (err) {
        return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify({ code: 'FETCH_ERROR', message: String(err) }) }] };
      }
    }

    if (request.params.name === "list_org_members") {
      const input = ListOrgMembersInputSchema.parse(request.params.arguments ?? {});
      let url = "https://api.bitwarden.com/public/members";
      try {
        const res = await fetch(url, {
          method: "GET",
          headers: {
            'Content-Type': 'application/json',
            'Authorization': 'Bearer ' + (process.env['API_KEY'] ?? ''),
          },
          
        });
        const data = res.status === 204 ? {} : await res.json().catch(() => ({}));
        if (!res.ok) return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
        return { content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
      } catch (err) {
        return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify({ code: 'FETCH_ERROR', message: String(err) }) }] };
      }
    }

    if (request.params.name === "invite_org_member") {
      const input = InviteOrgMemberInputSchema.parse(request.params.arguments ?? {});
      let url = "https://api.bitwarden.com/public/members";
      const bodyKeys = new Set([]);
      const bodyPayload = Object.fromEntries(Object.entries(input).filter(([k]) => !bodyKeys.has(k)));
      try {
        const res = await fetch(url, {
          method: "POST",
          headers: {
            'Content-Type': 'application/json',
            'Authorization': 'Bearer ' + (process.env['API_KEY'] ?? ''),
          },
          body: JSON.stringify(bodyPayload),
        });
        const data = res.status === 204 ? {} : await res.json().catch(() => ({}));
        if (!res.ok) return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
        return { content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
      } catch (err) {
        return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify({ code: 'FETCH_ERROR', message: String(err) }) }] };
      }
    }

    if (request.params.name === "get_org_member") {
      const input = GetOrgMemberInputSchema.parse(request.params.arguments ?? {});
      let url = "https://api.bitwarden.com/public/members/{id}";
      url = url.replace('{id}', encodeURIComponent(String(input.id)));
      try {
        const res = await fetch(url, {
          method: "GET",
          headers: {
            'Content-Type': 'application/json',
            'Authorization': 'Bearer ' + (process.env['API_KEY'] ?? ''),
          },
          
        });
        const data = res.status === 204 ? {} : await res.json().catch(() => ({}));
        if (!res.ok) return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
        return { content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
      } catch (err) {
        return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify({ code: 'FETCH_ERROR', message: String(err) }) }] };
      }
    }

    if (request.params.name === "update_org_member") {
      const input = UpdateOrgMemberInputSchema.parse(request.params.arguments ?? {});
      let url = "https://api.bitwarden.com/public/members/{id}";
      url = url.replace('{id}', encodeURIComponent(String(input.id)));
      const bodyKeys = new Set(["id"]);
      const bodyPayload = Object.fromEntries(Object.entries(input).filter(([k]) => !bodyKeys.has(k)));
      try {
        const res = await fetch(url, {
          method: "PUT",
          headers: {
            'Content-Type': 'application/json',
            'Authorization': 'Bearer ' + (process.env['API_KEY'] ?? ''),
          },
          body: JSON.stringify(bodyPayload),
        });
        const data = res.status === 204 ? {} : await res.json().catch(() => ({}));
        if (!res.ok) return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
        return { content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
      } catch (err) {
        return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify({ code: 'FETCH_ERROR', message: String(err) }) }] };
      }
    }

    if (request.params.name === "remove_org_member") {
      const input = RemoveOrgMemberInputSchema.parse(request.params.arguments ?? {});
      let url = "https://api.bitwarden.com/public/members/{id}";
      url = url.replace('{id}', encodeURIComponent(String(input.id)));
      try {
        const res = await fetch(url, {
          method: "DELETE",
          headers: {
            'Content-Type': 'application/json',
            'Authorization': 'Bearer ' + (process.env['API_KEY'] ?? ''),
          },
          
        });
        const data = res.status === 204 ? {} : await res.json().catch(() => ({}));
        if (!res.ok) return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
        return { content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
      } catch (err) {
        return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify({ code: 'FETCH_ERROR', message: String(err) }) }] };
      }
    }

    if (request.params.name === "reinvite_org_member") {
      const input = ReinviteOrgMemberInputSchema.parse(request.params.arguments ?? {});
      let url = "https://api.bitwarden.com/public/members/{id}/reinvite";
      url = url.replace('{id}', encodeURIComponent(String(input.id)));
      try {
        const res = await fetch(url, {
          method: "POST",
          headers: {
            'Content-Type': 'application/json',
            'Authorization': 'Bearer ' + (process.env['API_KEY'] ?? ''),
          },
          
        });
        const data = res.status === 204 ? {} : await res.json().catch(() => ({}));
        if (!res.ok) return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
        return { content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
      } catch (err) {
        return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify({ code: 'FETCH_ERROR', message: String(err) }) }] };
      }
    }

    if (request.params.name === "confirm_org_member") {
      const input = ConfirmOrgMemberInputSchema.parse(request.params.arguments ?? {});
      let url = "https://api.bitwarden.com/public/members/{id}/confirm";
      url = url.replace('{id}', encodeURIComponent(String(input.id)));
      const bodyKeys = new Set(["id"]);
      const bodyPayload = Object.fromEntries(Object.entries(input).filter(([k]) => !bodyKeys.has(k)));
      try {
        const res = await fetch(url, {
          method: "POST",
          headers: {
            'Content-Type': 'application/json',
            'Authorization': 'Bearer ' + (process.env['API_KEY'] ?? ''),
          },
          body: JSON.stringify(bodyPayload),
        });
        const data = res.status === 204 ? {} : await res.json().catch(() => ({}));
        if (!res.ok) return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
        return { content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
      } catch (err) {
        return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify({ code: 'FETCH_ERROR', message: String(err) }) }] };
      }
    }

    if (request.params.name === "list_org_groups") {
      const input = ListOrgGroupsInputSchema.parse(request.params.arguments ?? {});
      let url = "https://api.bitwarden.com/public/groups";
      try {
        const res = await fetch(url, {
          method: "GET",
          headers: {
            'Content-Type': 'application/json',
            'Authorization': 'Bearer ' + (process.env['API_KEY'] ?? ''),
          },
          
        });
        const data = res.status === 204 ? {} : await res.json().catch(() => ({}));
        if (!res.ok) return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
        return { content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
      } catch (err) {
        return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify({ code: 'FETCH_ERROR', message: String(err) }) }] };
      }
    }

    if (request.params.name === "create_org_group") {
      const input = CreateOrgGroupInputSchema.parse(request.params.arguments ?? {});
      let url = "https://api.bitwarden.com/public/groups";
      const bodyKeys = new Set([]);
      const bodyPayload = Object.fromEntries(Object.entries(input).filter(([k]) => !bodyKeys.has(k)));
      try {
        const res = await fetch(url, {
          method: "POST",
          headers: {
            'Content-Type': 'application/json',
            'Authorization': 'Bearer ' + (process.env['API_KEY'] ?? ''),
          },
          body: JSON.stringify(bodyPayload),
        });
        const data = res.status === 204 ? {} : await res.json().catch(() => ({}));
        if (!res.ok) return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
        return { content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
      } catch (err) {
        return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify({ code: 'FETCH_ERROR', message: String(err) }) }] };
      }
    }

    if (request.params.name === "get_org_group") {
      const input = GetOrgGroupInputSchema.parse(request.params.arguments ?? {});
      let url = "https://api.bitwarden.com/public/groups/{id}";
      url = url.replace('{id}', encodeURIComponent(String(input.id)));
      try {
        const res = await fetch(url, {
          method: "GET",
          headers: {
            'Content-Type': 'application/json',
            'Authorization': 'Bearer ' + (process.env['API_KEY'] ?? ''),
          },
          
        });
        const data = res.status === 204 ? {} : await res.json().catch(() => ({}));
        if (!res.ok) return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
        return { content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
      } catch (err) {
        return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify({ code: 'FETCH_ERROR', message: String(err) }) }] };
      }
    }

    if (request.params.name === "update_org_group") {
      const input = UpdateOrgGroupInputSchema.parse(request.params.arguments ?? {});
      let url = "https://api.bitwarden.com/public/groups/{id}";
      url = url.replace('{id}', encodeURIComponent(String(input.id)));
      const bodyKeys = new Set(["id"]);
      const bodyPayload = Object.fromEntries(Object.entries(input).filter(([k]) => !bodyKeys.has(k)));
      try {
        const res = await fetch(url, {
          method: "PUT",
          headers: {
            'Content-Type': 'application/json',
            'Authorization': 'Bearer ' + (process.env['API_KEY'] ?? ''),
          },
          body: JSON.stringify(bodyPayload),
        });
        const data = res.status === 204 ? {} : await res.json().catch(() => ({}));
        if (!res.ok) return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
        return { content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
      } catch (err) {
        return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify({ code: 'FETCH_ERROR', message: String(err) }) }] };
      }
    }

    if (request.params.name === "delete_org_group") {
      const input = DeleteOrgGroupInputSchema.parse(request.params.arguments ?? {});
      let url = "https://api.bitwarden.com/public/groups/{id}";
      url = url.replace('{id}', encodeURIComponent(String(input.id)));
      try {
        const res = await fetch(url, {
          method: "DELETE",
          headers: {
            'Content-Type': 'application/json',
            'Authorization': 'Bearer ' + (process.env['API_KEY'] ?? ''),
          },
          
        });
        const data = res.status === 204 ? {} : await res.json().catch(() => ({}));
        if (!res.ok) return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
        return { content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
      } catch (err) {
        return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify({ code: 'FETCH_ERROR', message: String(err) }) }] };
      }
    }

    if (request.params.name === "get_org_group_member_ids") {
      const input = GetOrgGroupMemberIdsInputSchema.parse(request.params.arguments ?? {});
      let url = "https://api.bitwarden.com/public/groups/{id}/member-ids";
      url = url.replace('{id}', encodeURIComponent(String(input.id)));
      try {
        const res = await fetch(url, {
          method: "GET",
          headers: {
            'Content-Type': 'application/json',
            'Authorization': 'Bearer ' + (process.env['API_KEY'] ?? ''),
          },
          
        });
        const data = res.status === 204 ? {} : await res.json().catch(() => ({}));
        if (!res.ok) return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
        return { content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
      } catch (err) {
        return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify({ code: 'FETCH_ERROR', message: String(err) }) }] };
      }
    }

    if (request.params.name === "update_org_group_members") {
      const input = UpdateOrgGroupMembersInputSchema.parse(request.params.arguments ?? {});
      let url = "https://api.bitwarden.com/public/groups/{id}/member-ids";
      url = url.replace('{id}', encodeURIComponent(String(input.id)));
      const bodyKeys = new Set(["id"]);
      const bodyPayload = Object.fromEntries(Object.entries(input).filter(([k]) => !bodyKeys.has(k)));
      try {
        const res = await fetch(url, {
          method: "PUT",
          headers: {
            'Content-Type': 'application/json',
            'Authorization': 'Bearer ' + (process.env['API_KEY'] ?? ''),
          },
          body: JSON.stringify(bodyPayload),
        });
        const data = res.status === 204 ? {} : await res.json().catch(() => ({}));
        if (!res.ok) return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
        return { content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
      } catch (err) {
        return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify({ code: 'FETCH_ERROR', message: String(err) }) }] };
      }
    }

    if (request.params.name === "get_org_events") {
      const input = GetOrgEventsInputSchema.parse(request.params.arguments ?? {});
      let url = "https://api.bitwarden.com/public/events";
      const qs = new URLSearchParams();
      if (input.start !== undefined) qs.set('start', String(input.start));
      if (input.end !== undefined) qs.set('end', String(input.end));
      if (input.continuationToken !== undefined) qs.set('continuationToken', String(input.continuationToken));
      if (qs.toString()) url += '?' + qs.toString();
      try {
        const res = await fetch(url, {
          method: "GET",
          headers: {
            'Content-Type': 'application/json',
            'Authorization': 'Bearer ' + (process.env['API_KEY'] ?? ''),
          },
          
        });
        const data = res.status === 204 ? {} : await res.json().catch(() => ({}));
        if (!res.ok) return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
        return { content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
      } catch (err) {
        return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify({ code: 'FETCH_ERROR', message: String(err) }) }] };
      }
    }

    if (request.params.name === "list_org_policies") {
      const input = ListOrgPoliciesInputSchema.parse(request.params.arguments ?? {});
      let url = "https://api.bitwarden.com/public/policies";
      try {
        const res = await fetch(url, {
          method: "GET",
          headers: {
            'Content-Type': 'application/json',
            'Authorization': 'Bearer ' + (process.env['API_KEY'] ?? ''),
          },
          
        });
        const data = res.status === 204 ? {} : await res.json().catch(() => ({}));
        if (!res.ok) return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
        return { content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
      } catch (err) {
        return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify({ code: 'FETCH_ERROR', message: String(err) }) }] };
      }
    }

    if (request.params.name === "get_org_policy") {
      const input = GetOrgPolicyInputSchema.parse(request.params.arguments ?? {});
      let url = "https://api.bitwarden.com/public/policies/{type}";
      url = url.replace('{type}', encodeURIComponent(String(input.type)));
      try {
        const res = await fetch(url, {
          method: "GET",
          headers: {
            'Content-Type': 'application/json',
            'Authorization': 'Bearer ' + (process.env['API_KEY'] ?? ''),
          },
          
        });
        const data = res.status === 204 ? {} : await res.json().catch(() => ({}));
        if (!res.ok) return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
        return { content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
      } catch (err) {
        return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify({ code: 'FETCH_ERROR', message: String(err) }) }] };
      }
    }

    if (request.params.name === "update_org_policy") {
      const input = UpdateOrgPolicyInputSchema.parse(request.params.arguments ?? {});
      let url = "https://api.bitwarden.com/public/policies/{type}";
      url = url.replace('{type}', encodeURIComponent(String(input.type)));
      const bodyKeys = new Set(["type"]);
      const bodyPayload = Object.fromEntries(Object.entries(input).filter(([k]) => !bodyKeys.has(k)));
      try {
        const res = await fetch(url, {
          method: "PUT",
          headers: {
            'Content-Type': 'application/json',
            'Authorization': 'Bearer ' + (process.env['API_KEY'] ?? ''),
          },
          body: JSON.stringify(bodyPayload),
        });
        const data = res.status === 204 ? {} : await res.json().catch(() => ({}));
        if (!res.ok) return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
        return { content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
      } catch (err) {
        return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify({ code: 'FETCH_ERROR', message: String(err) }) }] };
      }
    }

  return {
    isError: true,
    content: [{ type: 'text' as const, text: `Unknown tool: ${request.params.name}` }],
  };
});

// ── Boot ─────────────────────────────────────────────────────────────────────

async function main() {
  const transport = new StdioServerTransport();
  await server.connect(transport);
  process.stderr.write('bitwarden-mcp MCP server running on stdio\n');
}

main().catch((err) => {
  process.stderr.write(`Fatal: ${err instanceof Error ? err.message : String(err)}\n`);
  process.exit(1);
});
