#!/usr/bin/env bash
# gitmoji-enforce.sh — commit-msg stage gate.
# Rejects any first-line commit message lacking a leading gitmoji or emoji.
# Belt+suspenders companion to commitlint (commitlint validates type/scope shape;
# this script catches the literal emoji presence).
#
# Usage (lefthook commit-msg): bash ~/.agentskills/templates/lint-stack/scripts/gitmoji-enforce.sh {1}
# Where {1} is the path to .git/COMMIT_EDITMSG passed by lefthook.

set -euo pipefail

MSG_FILE="${1:?commit-msg file path required as arg 1}"
[ -r "$MSG_FILE" ] || { echo "ERROR: cannot read $MSG_FILE" >&2; exit 1; }

msg=$(head -n1 "$MSG_FILE")

# Accept three forms:
#   1. :name: gitmoji shortcode (e.g. :sparkles:, :bug:, :rocket:)
#   2. Unicode emoji ranges (F300-FAFF + 2600-26FF cover most gitmoji-relevant glyphs)
#   3. Lefthook bypass marker (allow `Revert ...` and `Merge ...` auto-generated msgs)
if echo "$msg" | grep -qE '^[:][a-z0-9_]+[:]'; then
  exit 0  # shortcode form
fi
if command -v perl >/dev/null 2>&1; then
  if echo "$msg" | perl -CSD -ne 'exit 0 if /^[\x{1F300}-\x{1FAFF}\x{2600}-\x{26FF}\x{2700}-\x{27BF}]/; exit 1'; then
    exit 0  # unicode form (perl path)
  fi
elif command -v python3 >/dev/null 2>&1; then
  if echo "$msg" | python3 -c "import sys,re; sys.exit(0 if re.match(r'^[\U0001F300-\U0001FAFF☀-⛿✀-➿]', sys.stdin.read()) else 1)"; then
    exit 0  # unicode form (python3 fallback)
  fi
fi
if echo "$msg" | grep -qE '^(Revert |Merge (branch|pull request|tag|remote-tracking))'; then
  exit 0  # auto-generated bypass
fi

cat >&2 <<EOF
ERROR: commit message must start with a gitmoji or emoji shortcode.
   bad: $msg

   fix: prefix with one of these (or use 'git cz' for guided commit)
     ✨ :sparkles:  — new feature
     🐛 :bug:       — bug fix
     📝 :memo:      — docs
     ♻️  :recycle:   — refactor
     🔧 :wrench:    — config
     🚀 :rocket:    — deploy
     ⚡ :zap:       — perf
     ✅ :white_check_mark: — tests
     🔥 :fire:      — remove code
     🔖 :bookmark:  — release/tag

Full gitmoji list: https://gitmoji.dev
EOF
exit 1
