// src/rate-limiter.ts
// Auto-generated by forge-skill-from-openapi --harden
// stdio transport: Durable Object rate limiter not applicable.
// Implement in-process rate limiting here if needed (e.g. a token bucket per tool).
