// src/scrub-pii.ts
// Auto-generated by forge-skill-from-openapi --harden
// Redact PII / secrets from args + responses before audit logging

const REDACT_KEYS = /^(token|secret|key|password|auth|bearer|ssn|cc_number|card|api_key|apikey|access_token|refresh_token|private_key)/i;
const REDACT_PATTERNS = [
  /\b\d{4}[- ]?\d{4}[- ]?\d{4}[- ]?\d{4}\b/g,           // credit card
  /\b\d{3}-\d{2}-\d{4}\b/g,                               // SSN
  /\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b/g, // email
  /\+?[\d\s\-().]{10,}/g,                                  // phone
  /Bearer\s+[A-Za-z0-9\-._~+/]+=*/gi,                       // bearer token
];

export function redactPii(value: unknown, depth = 0): unknown {
  if (depth > 6) return '[truncated]';
  if (value === null || value === undefined) return value;
  if (typeof value === 'string') {
    let s = value;
    for (const pattern of REDACT_PATTERNS) s = s.replace(pattern, '[REDACTED]');
    return s;
  }
  if (Array.isArray(value)) return value.map(v => redactPii(v, depth + 1));
  if (typeof value === 'object') {
    const out: Record<string, unknown> = {};
    for (const [k, v] of Object.entries(value as Record<string, unknown>)) {
      out[k] = REDACT_KEYS.test(k) ? '[REDACTED]' : redactPii(v, depth + 1);
    }
    return out;
  }
  return value;
}
