// Auto-generated by forge-skill-from-openapi --target=mcp-server --transport=stdio
// API: posthog-mcp
// DO NOT EDIT — re-run forge to regenerate

import { Server } from '@modelcontextprotocol/sdk/server/index.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import { CallToolRequestSchema, ListToolsRequestSchema } from '@modelcontextprotocol/sdk/types.js';
import { z } from 'zod';

// ── Zod input schemas (one per operation) ────────────────────────────────────

export const EnvironmentsDashboardsListInputSchema = z.object({
  format: z.string().optional(),
  limit: z.number().int().optional(),
  offset: z.number().int().optional(),
  search: z.string().optional(),
}).strict();

export const EnvironmentsEventsListInputSchema = z.object({
  after: z.string().optional(),
  before: z.string().optional(),
  distinct_id: z.number().int().optional(),
  event: z.string().optional(),
  format: z.string().optional(),
  include_person: z.boolean().optional(),
  limit: z.number().int().optional(),
  offset: z.number().int().optional(),
  person_id: z.number().int().optional(),
  properties: z.array(z.unknown()).optional(),
  select: z.array(z.unknown()).optional(),
  where: z.array(z.unknown()).optional(),
}).strict();

export const EnvironmentsInsightsListInputSchema = z.object({
  basic: z.boolean().optional(),
  created_by: z.string().optional(),
  created_date_from: z.string().optional(),
  created_date_to: z.string().optional(),
  dashboards: z.string().optional(),
  date_from: z.string().optional(),
  date_to: z.string().optional(),
  favorited: z.boolean().optional(),
  format: z.string().optional(),
  insight: z.string().optional(),
  last_viewed_date_from: z.string().optional(),
  last_viewed_date_to: z.string().optional(),
  limit: z.number().int().optional(),
  offset: z.number().int().optional(),
  refresh: z.string().optional(),
  saved: z.boolean().optional(),
  search: z.string().optional(),
  short_id: z.string().optional(),
  tags: z.string().optional(),
  user: z.boolean().optional(),
}).strict();

export const EnvironmentsInsightsCreateInputSchema = z.object({
  format: z.string().optional(),
}).strict();

export const EnvironmentsPersonsListInputSchema = z.object({
  distinct_id: z.string().optional(),
  email: z.string().optional(),
  format: z.string().optional(),
  limit: z.number().int().optional(),
  offset: z.number().int().optional(),
  properties: z.array(z.unknown()).optional(),
  search: z.string().optional(),
}).strict();

export const EnvironmentsQueryCreateInputSchema = z.object({}).strict();

export const CohortsCreateInputSchema = z.object({}).strict();

export const ExperimentsListInputSchema = z.object({
  archived: z.boolean().optional(),
  created_by_id: z.number().int().optional(),
  feature_flag_id: z.number().int().optional(),
  limit: z.number().int().optional(),
  offset: z.number().int().optional(),
  order: z.string().optional(),
  prompt_name: z.string().optional(),
  search: z.string().optional(),
  status: z.string().optional(),
}).strict();

export const ExperimentsCreateInputSchema = z.object({}).strict();

export const FeatureFlagsListInputSchema = z.object({
  active: z.string().optional(),
  created_by_id: z.string().optional(),
  evaluation_runtime: z.string().optional(),
  excluded_properties: z.string().optional(),
  has_evaluation_contexts: z.string().optional(),
  limit: z.number().int().optional(),
  offset: z.number().int().optional(),
  search: z.string().optional(),
  tags: z.string().optional(),
  type: z.string().optional(),
}).strict();

export const FeatureFlagsCreateInputSchema = z.object({}).strict();

export const FeatureFlagsRetrieveInputSchema = z.object({
  id: z.number().int(),
}).strict();

export const FeatureFlagsUpdateInputSchema = z.object({
  id: z.number().int(),
}).strict();




















































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































// ── Server init ──────────────────────────────────────────────────────────────

const server = new Server(
  { name: "posthog-mcp", version: '1.0.0' },
  { capabilities: { tools: {} } },
);

// ── ListTools ─────────────────────────────────────────────────────────────────

server.setRequestHandler(ListToolsRequestSchema, async () => ({
  tools: [
{
    "name": "environments_dashboards_list",
    "description": "GET /api/environments/{environment_id}/dashboards/",
    "inputSchema": {
      "type": "object",
      "properties": {
        "format": {
          "type": "string",
          "description": "format"
        },
        "limit": {
          "type": "integer",
          "description": "Number of results to return per page."
        },
        "offset": {
          "type": "integer",
          "description": "The initial index from which to return the results."
        },
        "search": {
          "type": "string",
          "description": "Optional. Fuzzy match against dashboard `name` and `description` using Postgres trigram word similarity (handles typos, transpositions, and prefix-as-you-type). `name` matches rank above `description` matches. Results are ordered by relevance, then pinned status, then name. When omitted, dashboards are ordered by pinned status then alphabetical name. Capped at 200 characters; longer queries return a 400 error."
        }
      }
    }
  },
{
    "name": "environments_events_list",
    "description": "\n        This endpoint allows you to list and filter events.\n        It is effectively deprecated and is kept only for backwards compatibility.\n        If you ever ask about it you will be advised to not use it...\n        If you want to ad-hoc list or aggregate events, use the Query endpoint instead.\n        If you want to export all events or many pages of events you should use our CDP/Batch Exports products instead.\n        ",
    "inputSchema": {
      "type": "object",
      "properties": {
        "after": {
          "type": "string",
          "description": "Only return events with a timestamp after this time. Default: now() - 24 hours."
        },
        "before": {
          "type": "string",
          "description": "Only return events with a timestamp before this time. Default: now() + 5 seconds."
        },
        "distinct_id": {
          "type": "integer",
          "description": "Filter list by distinct id."
        },
        "event": {
          "type": "string",
          "description": "Filter list by event. For example `user sign up` or `$pageview`."
        },
        "format": {
          "type": "string",
          "description": "format"
        },
        "include_person": {
          "type": "boolean",
          "description": "Include person details for each event. Default: false."
        },
        "limit": {
          "type": "integer",
          "description": "The maximum number of results to return"
        },
        "offset": {
          "type": "integer",
          "description": "Allows to skip first offset rows. Will fail for value larger than 100000. Read about proper way of paginating: https://posthog.com/docs/api/queries#5-use-timestamp-based-pagination-instead-of-offset"
        },
        "person_id": {
          "type": "integer",
          "description": "Filter list by person id."
        },
        "properties": {
          "type": "array",
          "description": "Filter events by event property, person property, cohort, groups and more."
        },
        "select": {
          "type": "array",
          "description": "(Experimental) JSON-serialized array of HogQL expressions to return"
        },
        "where": {
          "type": "array",
          "description": "(Experimental) JSON-serialized array of HogQL expressions that must pass"
        }
      }
    }
  },
{
    "name": "environments_insights_list",
    "description": "DRF ViewSet mixin that gates coalesced responses behind permission checks.\n\nThe QueryCoalescingMiddleware attaches cached response data to\nrequest.META[\"_coalesced_response\"] for followers. This mixin runs DRF's\ninitial() (auth + permissions + throttling) before returning the\ncached response, ensuring the request is authorized.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "basic": {
          "type": "boolean",
          "description": "Return basic insight metadata only (no results, faster)."
        },
        "created_by": {
          "type": "string",
          "description": "JSON-encoded array of user IDs. Only returns insights whose `created_by` is in the list, e.g. `[1,42]`."
        },
        "created_date_from": {
          "type": "string",
          "description": "Filter by `created_at > created_date_from`. Accepts absolute or relative dates."
        },
        "created_date_to": {
          "type": "string",
          "description": "Filter by `created_at < created_date_to`. Accepts absolute or relative dates."
        },
        "dashboards": {
          "type": "string",
          "description": "JSON-encoded array of dashboard IDs. Returns insights attached to every listed dashboard (AND)."
        },
        "date_from": {
          "type": "string",
          "description": "Filter by `last_modified_at > date_from`. Accepts absolute dates (`2025-04-23`) or relative strings (`-7d`, `-1m`)."
        },
        "date_to": {
          "type": "string",
          "description": "Filter by `last_modified_at < date_to`. Accepts absolute dates or relative strings."
        },
        "favorited": {
          "type": "boolean",
          "description": "Include this parameter (any value) to restrict results to insights marked as favorited."
        },
        "format": {
          "type": "string",
          "description": "format"
        },
        "insight": {
          "type": "string",
          "description": "Restrict to a single insight type. `JSON` matches non-wrapper query insights; `SQL` matches HogQL queries."
        },
        "last_viewed_date_from": {
          "type": "string",
          "description": "Filter by `last_viewed_at > last_viewed_date_from`. Accepts absolute or relative dates."
        },
        "last_viewed_date_to": {
          "type": "string",
          "description": "Filter by `last_viewed_at < last_viewed_date_to`. Accepts absolute or relative dates."
        },
        "limit": {
          "type": "integer",
          "description": "Number of results to return per page."
        },
        "offset": {
          "type": "integer",
          "description": "The initial index from which to return the results."
        },
        "refresh": {
          "type": "string",
          "description": "\nWhether to refresh the retrieved insights, how aggressively, and if sync or async:\n- `'force_cache'` - return cached data or a cache miss; always completes immediately as it never calculates\n- `'blocking'` - calculate synchronously (returning only when the query is done), UNLESS there are very fresh results in the cache\n- `'async'` - kick off background calculation (returning immediately with a query status), UNLESS there are very fresh results in the cache\n- `'lazy_async'` - kick off background calculation, UNLESS there are somewhat fresh results in the cache\n- `'force_blocking'` - calculate synchronously, even if fresh results are already cached\n- `'force_async'` - kick off background calculation, even if fresh results are already cached\nBackground calculation can be tracked using the `query_status` response field."
        },
        "saved": {
          "type": "boolean",
          "description": "When truthy, restricts results to insights that are saved (or attached to a visible dashboard). When falsy, only unsaved insights."
        },
        "search": {
          "type": "string",
          "description": "Case-insensitive substring match across name, derived_name, description, and tag names."
        },
        "short_id": {
          "type": "string",
          "description": "short_id"
        },
        "tags": {
          "type": "string",
          "description": "JSON-encoded array of tag names. Returns insights with any of the listed tags."
        },
        "user": {
          "type": "boolean",
          "description": "Include this parameter (any value) to restrict results to insights created by the authenticated user."
        }
      }
    }
  },
{
    "name": "environments_insights_create",
    "description": "DRF ViewSet mixin that gates coalesced responses behind permission checks.\n\nThe QueryCoalescingMiddleware attaches cached response data to\nrequest.META[\"_coalesced_response\"] for followers. This mixin runs DRF's\ninitial() (auth + permissions + throttling) before returning the\ncached response, ensuring the request is authorized.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "format": {
          "type": "string",
          "description": "format"
        }
      }
    }
  },
{
    "name": "environments_persons_list",
    "description": "This endpoint is meant for reading and deleting persons. To create or update persons, we recommend using the [capture API](https://posthog.com/docs/api/capture), the `$set` and `$unset` [properties](https://posthog.com/docs/product-analytics/user-properties), or one of our SDKs.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "distinct_id": {
          "type": "string",
          "description": "Filter list by distinct id."
        },
        "email": {
          "type": "string",
          "description": "Filter persons by email (exact match)"
        },
        "format": {
          "type": "string",
          "description": "format"
        },
        "limit": {
          "type": "integer",
          "description": "Number of results to return per page."
        },
        "offset": {
          "type": "integer",
          "description": "The initial index from which to return the results."
        },
        "properties": {
          "type": "array",
          "description": "Filter Persons by person properties."
        },
        "search": {
          "type": "string",
          "description": "Search persons, either by email (full text search) or distinct_id (exact match)."
        }
      }
    }
  },
{
    "name": "environments_query_create",
    "description": "DRF ViewSet mixin that gates coalesced responses behind permission checks.\n\nThe QueryCoalescingMiddleware attaches cached response data to\nrequest.META[\"_coalesced_response\"] for followers. This mixin runs DRF's\ninitial() (auth + permissions + throttling) before returning the\ncached response, ensuring the request is authorized.",
    "inputSchema": {
      "type": "object",
      "properties": {}
    }
  },
{
    "name": "cohorts_create",
    "description": "POST /api/projects/{project_id}/cohorts/",
    "inputSchema": {
      "type": "object",
      "properties": {}
    }
  },
{
    "name": "experiments_list",
    "description": "List experiments for the current project. Supports filtering by status and archival state.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "archived": {
          "type": "boolean",
          "description": "Filter by archived state. Defaults to non-archived experiments only."
        },
        "created_by_id": {
          "type": "integer",
          "description": "Filter to experiments created by the given user ID."
        },
        "feature_flag_id": {
          "type": "integer",
          "description": "Filter to experiments linked to the given feature flag ID."
        },
        "limit": {
          "type": "integer",
          "description": "Number of results to return per page."
        },
        "offset": {
          "type": "integer",
          "description": "The initial index from which to return the results."
        },
        "order": {
          "type": "string",
          "description": "Field to order by. Prefix with '-' for descending. Allowlisted fields include name, created_at, updated_at, start_date, end_date, duration, and status."
        },
        "prompt_name": {
          "type": "string",
          "description": "Filter to experiments created from an LLM prompt with this name. Matches experiments whose parameters.prompt_metadata.name equals the given value."
        },
        "search": {
          "type": "string",
          "description": "Free-text search applied to the experiment name (case-insensitive)."
        },
        "status": {
          "type": "string",
          "description": "Filter by experiment status. \"running\" and \"paused\" are mutually exclusive: \"running\" returns launched experiments with an active feature flag, \"paused\" returns launched experiments whose feature flag is deactivated. \"complete\" is an alias for \"stopped\". \"all\" disables status filtering."
        }
      }
    }
  },
{
    "name": "experiments_create",
    "description": "Create a new experiment in draft status with optional metrics.",
    "inputSchema": {
      "type": "object",
      "properties": {}
    }
  },
{
    "name": "feature_flags_list",
    "description": "Create, read, update and delete feature flags. [See docs](https://posthog.com/docs/feature-flags) for more information on feature flags.\n\nIf you're looking to use feature flags on your application, you can either use our JavaScript Library or our dedicated endpoint to check if feature flags are enabled for a given user.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "active": {
          "type": "string",
          "description": "active"
        },
        "created_by_id": {
          "type": "string",
          "description": "The User ID which initially created the feature flag."
        },
        "evaluation_runtime": {
          "type": "string",
          "description": "Filter feature flags by their evaluation runtime."
        },
        "excluded_properties": {
          "type": "string",
          "description": "JSON-encoded list of feature flag keys to exclude from the results."
        },
        "has_evaluation_contexts": {
          "type": "string",
          "description": "Filter feature flags by presence of evaluation contexts. 'true' returns only flags with at least one evaluation context, 'false' returns only flags without."
        },
        "limit": {
          "type": "integer",
          "description": "Number of results to return per page."
        },
        "offset": {
          "type": "integer",
          "description": "The initial index from which to return the results."
        },
        "search": {
          "type": "string",
          "description": "Search by feature flag key or name. Case insensitive."
        },
        "tags": {
          "type": "string",
          "description": "JSON-encoded list of tag names to filter feature flags by."
        },
        "type": {
          "type": "string",
          "description": "type"
        }
      }
    }
  },
{
    "name": "feature_flags_create",
    "description": "Create, read, update and delete feature flags. [See docs](https://posthog.com/docs/feature-flags) for more information on feature flags.\n\nIf you're looking to use feature flags on your application, you can either use our JavaScript Library or our dedicated endpoint to check if feature flags are enabled for a given user.",
    "inputSchema": {
      "type": "object",
      "properties": {}
    }
  },
{
    "name": "feature_flags_retrieve",
    "description": "Create, read, update and delete feature flags. [See docs](https://posthog.com/docs/feature-flags) for more information on feature flags.\n\nIf you're looking to use feature flags on your application, you can either use our JavaScript Library or our dedicated endpoint to check if feature flags are enabled for a given user.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer",
          "description": "A unique integer value identifying this feature flag."
        }
      },
      "required": [
        "id"
      ]
    }
  },
{
    "name": "feature_flags_update",
    "description": "Create, read, update and delete feature flags. [See docs](https://posthog.com/docs/feature-flags) for more information on feature flags.\n\nIf you're looking to use feature flags on your application, you can either use our JavaScript Library or our dedicated endpoint to check if feature flags are enabled for a given user.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer",
          "description": "A unique integer value identifying this feature flag."
        }
      },
      "required": [
        "id"
      ]
    }
  }
  ],
}));

// ── CallTool ──────────────────────────────────────────────────────────────────

server.setRequestHandler(CallToolRequestSchema, async (request) => {






























    if (request.params.name === "environments_dashboards_list") {
      const input = EnvironmentsDashboardsListInputSchema.parse(request.params.arguments ?? {});
      let url = "/api/environments/{environment_id}/dashboards/";
      const qs = new URLSearchParams();
      if (input.format !== undefined) qs.set('format', String(input.format));
      if (input.limit !== undefined) qs.set('limit', String(input.limit));
      if (input.offset !== undefined) qs.set('offset', String(input.offset));
      if (input.search !== undefined) qs.set('search', String(input.search));
      if (qs.toString()) url += '?' + qs.toString();
      try {
        const res = await fetch(url, {
          method: "GET",
          headers: {
            'Content-Type': 'application/json',
            'Authorization': 'Bearer ' + (process.env['API_KEY'] ?? ''),
          },
          
        });
        const data = res.status === 204 ? {} : await res.json().catch(() => ({}));
        if (!res.ok) return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
        return { content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
      } catch (err) {
        return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify({ code: 'FETCH_ERROR', message: String(err) }) }] };
      }
    }































































































    if (request.params.name === "environments_events_list") {
      const input = EnvironmentsEventsListInputSchema.parse(request.params.arguments ?? {});
      let url = "/api/environments/{environment_id}/events/";
      const qs = new URLSearchParams();
      if (input.after !== undefined) qs.set('after', String(input.after));
      if (input.before !== undefined) qs.set('before', String(input.before));
      if (input.distinct_id !== undefined) qs.set('distinct_id', String(input.distinct_id));
      if (input.event !== undefined) qs.set('event', String(input.event));
      if (input.format !== undefined) qs.set('format', String(input.format));
      if (input.include_person !== undefined) qs.set('include_person', String(input.include_person));
      if (input.limit !== undefined) qs.set('limit', String(input.limit));
      if (input.offset !== undefined) qs.set('offset', String(input.offset));
      if (input.person_id !== undefined) qs.set('person_id', String(input.person_id));
      if (input.properties !== undefined) qs.set('properties', String(input.properties));
      if (input.select !== undefined) qs.set('select', String(input.select));
      if (input.where !== undefined) qs.set('where', String(input.where));
      if (qs.toString()) url += '?' + qs.toString();
      try {
        const res = await fetch(url, {
          method: "GET",
          headers: {
            'Content-Type': 'application/json',
            'Authorization': 'Bearer ' + (process.env['API_KEY'] ?? ''),
          },
          
        });
        const data = res.status === 204 ? {} : await res.json().catch(() => ({}));
        if (!res.ok) return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
        return { content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
      } catch (err) {
        return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify({ code: 'FETCH_ERROR', message: String(err) }) }] };
      }
    }



















































































































    if (request.params.name === "environments_insights_list") {
      const input = EnvironmentsInsightsListInputSchema.parse(request.params.arguments ?? {});
      let url = "/api/environments/{environment_id}/insights/";
      const qs = new URLSearchParams();
      if (input.basic !== undefined) qs.set('basic', String(input.basic));
      if (input.created_by !== undefined) qs.set('created_by', String(input.created_by));
      if (input.created_date_from !== undefined) qs.set('created_date_from', String(input.created_date_from));
      if (input.created_date_to !== undefined) qs.set('created_date_to', String(input.created_date_to));
      if (input.dashboards !== undefined) qs.set('dashboards', String(input.dashboards));
      if (input.date_from !== undefined) qs.set('date_from', String(input.date_from));
      if (input.date_to !== undefined) qs.set('date_to', String(input.date_to));
      if (input.favorited !== undefined) qs.set('favorited', String(input.favorited));
      if (input.format !== undefined) qs.set('format', String(input.format));
      if (input.insight !== undefined) qs.set('insight', String(input.insight));
      if (input.last_viewed_date_from !== undefined) qs.set('last_viewed_date_from', String(input.last_viewed_date_from));
      if (input.last_viewed_date_to !== undefined) qs.set('last_viewed_date_to', String(input.last_viewed_date_to));
      if (input.limit !== undefined) qs.set('limit', String(input.limit));
      if (input.offset !== undefined) qs.set('offset', String(input.offset));
      if (input.refresh !== undefined) qs.set('refresh', String(input.refresh));
      if (input.saved !== undefined) qs.set('saved', String(input.saved));
      if (input.search !== undefined) qs.set('search', String(input.search));
      if (input.short_id !== undefined) qs.set('short_id', String(input.short_id));
      if (input.tags !== undefined) qs.set('tags', String(input.tags));
      if (input.user !== undefined) qs.set('user', String(input.user));
      if (qs.toString()) url += '?' + qs.toString();
      try {
        const res = await fetch(url, {
          method: "GET",
          headers: {
            'Content-Type': 'application/json',
            'Authorization': 'Bearer ' + (process.env['API_KEY'] ?? ''),
          },
          
        });
        const data = res.status === 204 ? {} : await res.json().catch(() => ({}));
        if (!res.ok) return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
        return { content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
      } catch (err) {
        return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify({ code: 'FETCH_ERROR', message: String(err) }) }] };
      }
    }

    if (request.params.name === "environments_insights_create") {
      const input = EnvironmentsInsightsCreateInputSchema.parse(request.params.arguments ?? {});
      let url = "/api/environments/{environment_id}/insights/";
      const qs = new URLSearchParams();
      if (input.format !== undefined) qs.set('format', String(input.format));
      if (qs.toString()) url += '?' + qs.toString();
      const bodyKeys = new Set(["format"]);
      const bodyPayload = Object.fromEntries(Object.entries(input).filter(([k]) => !bodyKeys.has(k)));
      try {
        const res = await fetch(url, {
          method: "POST",
          headers: {
            'Content-Type': 'application/json',
            'Authorization': 'Bearer ' + (process.env['API_KEY'] ?? ''),
          },
          body: JSON.stringify(bodyPayload),
        });
        const data = res.status === 204 ? {} : await res.json().catch(() => ({}));
        if (!res.ok) return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
        return { content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
      } catch (err) {
        return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify({ code: 'FETCH_ERROR', message: String(err) }) }] };
      }
    }
























































































    if (request.params.name === "environments_persons_list") {
      const input = EnvironmentsPersonsListInputSchema.parse(request.params.arguments ?? {});
      let url = "/api/environments/{environment_id}/persons/";
      const qs = new URLSearchParams();
      if (input.distinct_id !== undefined) qs.set('distinct_id', String(input.distinct_id));
      if (input.email !== undefined) qs.set('email', String(input.email));
      if (input.format !== undefined) qs.set('format', String(input.format));
      if (input.limit !== undefined) qs.set('limit', String(input.limit));
      if (input.offset !== undefined) qs.set('offset', String(input.offset));
      if (input.properties !== undefined) qs.set('properties', String(input.properties));
      if (input.search !== undefined) qs.set('search', String(input.search));
      if (qs.toString()) url += '?' + qs.toString();
      try {
        const res = await fetch(url, {
          method: "GET",
          headers: {
            'Content-Type': 'application/json',
            'Authorization': 'Bearer ' + (process.env['API_KEY'] ?? ''),
          },
          
        });
        const data = res.status === 204 ? {} : await res.json().catch(() => ({}));
        if (!res.ok) return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
        return { content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
      } catch (err) {
        return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify({ code: 'FETCH_ERROR', message: String(err) }) }] };
      }
    }
































    if (request.params.name === "environments_query_create") {
      const input = EnvironmentsQueryCreateInputSchema.parse(request.params.arguments ?? {});
      let url = "/api/environments/{environment_id}/query/";
      const bodyKeys = new Set([]);
      const bodyPayload = Object.fromEntries(Object.entries(input).filter(([k]) => !bodyKeys.has(k)));
      try {
        const res = await fetch(url, {
          method: "POST",
          headers: {
            'Content-Type': 'application/json',
            'Authorization': 'Bearer ' + (process.env['API_KEY'] ?? ''),
          },
          body: JSON.stringify(bodyPayload),
        });
        const data = res.status === 204 ? {} : await res.json().catch(() => ({}));
        if (!res.ok) return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
        return { content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
      } catch (err) {
        return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify({ code: 'FETCH_ERROR', message: String(err) }) }] };
      }
    }















































































































































































































































































































































































































































































































































    if (request.params.name === "cohorts_create") {
      const input = CohortsCreateInputSchema.parse(request.params.arguments ?? {});
      let url = "/api/projects/{project_id}/cohorts/";
      const bodyKeys = new Set([]);
      const bodyPayload = Object.fromEntries(Object.entries(input).filter(([k]) => !bodyKeys.has(k)));
      try {
        const res = await fetch(url, {
          method: "POST",
          headers: {
            'Content-Type': 'application/json',
            'Authorization': 'Bearer ' + (process.env['API_KEY'] ?? ''),
          },
          body: JSON.stringify(bodyPayload),
        });
        const data = res.status === 204 ? {} : await res.json().catch(() => ({}));
        if (!res.ok) return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
        return { content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
      } catch (err) {
        return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify({ code: 'FETCH_ERROR', message: String(err) }) }] };
      }
    }























































































































































































































    if (request.params.name === "experiments_list") {
      const input = ExperimentsListInputSchema.parse(request.params.arguments ?? {});
      let url = "/api/projects/{project_id}/experiments/";
      const qs = new URLSearchParams();
      if (input.archived !== undefined) qs.set('archived', String(input.archived));
      if (input.created_by_id !== undefined) qs.set('created_by_id', String(input.created_by_id));
      if (input.feature_flag_id !== undefined) qs.set('feature_flag_id', String(input.feature_flag_id));
      if (input.limit !== undefined) qs.set('limit', String(input.limit));
      if (input.offset !== undefined) qs.set('offset', String(input.offset));
      if (input.order !== undefined) qs.set('order', String(input.order));
      if (input.prompt_name !== undefined) qs.set('prompt_name', String(input.prompt_name));
      if (input.search !== undefined) qs.set('search', String(input.search));
      if (input.status !== undefined) qs.set('status', String(input.status));
      if (qs.toString()) url += '?' + qs.toString();
      try {
        const res = await fetch(url, {
          method: "GET",
          headers: {
            'Content-Type': 'application/json',
            'Authorization': 'Bearer ' + (process.env['API_KEY'] ?? ''),
          },
          
        });
        const data = res.status === 204 ? {} : await res.json().catch(() => ({}));
        if (!res.ok) return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
        return { content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
      } catch (err) {
        return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify({ code: 'FETCH_ERROR', message: String(err) }) }] };
      }
    }

    if (request.params.name === "experiments_create") {
      const input = ExperimentsCreateInputSchema.parse(request.params.arguments ?? {});
      let url = "/api/projects/{project_id}/experiments/";
      const bodyKeys = new Set([]);
      const bodyPayload = Object.fromEntries(Object.entries(input).filter(([k]) => !bodyKeys.has(k)));
      try {
        const res = await fetch(url, {
          method: "POST",
          headers: {
            'Content-Type': 'application/json',
            'Authorization': 'Bearer ' + (process.env['API_KEY'] ?? ''),
          },
          body: JSON.stringify(bodyPayload),
        });
        const data = res.status === 204 ? {} : await res.json().catch(() => ({}));
        if (!res.ok) return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
        return { content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
      } catch (err) {
        return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify({ code: 'FETCH_ERROR', message: String(err) }) }] };
      }
    }


























































    if (request.params.name === "feature_flags_list") {
      const input = FeatureFlagsListInputSchema.parse(request.params.arguments ?? {});
      let url = "/api/projects/{project_id}/feature_flags/";
      const qs = new URLSearchParams();
      if (input.active !== undefined) qs.set('active', String(input.active));
      if (input.created_by_id !== undefined) qs.set('created_by_id', String(input.created_by_id));
      if (input.evaluation_runtime !== undefined) qs.set('evaluation_runtime', String(input.evaluation_runtime));
      if (input.excluded_properties !== undefined) qs.set('excluded_properties', String(input.excluded_properties));
      if (input.has_evaluation_contexts !== undefined) qs.set('has_evaluation_contexts', String(input.has_evaluation_contexts));
      if (input.limit !== undefined) qs.set('limit', String(input.limit));
      if (input.offset !== undefined) qs.set('offset', String(input.offset));
      if (input.search !== undefined) qs.set('search', String(input.search));
      if (input.tags !== undefined) qs.set('tags', String(input.tags));
      if (input.type !== undefined) qs.set('type', String(input.type));
      if (qs.toString()) url += '?' + qs.toString();
      try {
        const res = await fetch(url, {
          method: "GET",
          headers: {
            'Content-Type': 'application/json',
            'Authorization': 'Bearer ' + (process.env['API_KEY'] ?? ''),
          },
          
        });
        const data = res.status === 204 ? {} : await res.json().catch(() => ({}));
        if (!res.ok) return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
        return { content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
      } catch (err) {
        return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify({ code: 'FETCH_ERROR', message: String(err) }) }] };
      }
    }

    if (request.params.name === "feature_flags_create") {
      const input = FeatureFlagsCreateInputSchema.parse(request.params.arguments ?? {});
      let url = "/api/projects/{project_id}/feature_flags/";
      const bodyKeys = new Set([]);
      const bodyPayload = Object.fromEntries(Object.entries(input).filter(([k]) => !bodyKeys.has(k)));
      try {
        const res = await fetch(url, {
          method: "POST",
          headers: {
            'Content-Type': 'application/json',
            'Authorization': 'Bearer ' + (process.env['API_KEY'] ?? ''),
          },
          body: JSON.stringify(bodyPayload),
        });
        const data = res.status === 204 ? {} : await res.json().catch(() => ({}));
        if (!res.ok) return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
        return { content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
      } catch (err) {
        return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify({ code: 'FETCH_ERROR', message: String(err) }) }] };
      }
    }

    if (request.params.name === "feature_flags_retrieve") {
      const input = FeatureFlagsRetrieveInputSchema.parse(request.params.arguments ?? {});
      let url = "/api/projects/{project_id}/feature_flags/{id}/";
      url = url.replace('{id}', encodeURIComponent(String(input.id)));
      try {
        const res = await fetch(url, {
          method: "GET",
          headers: {
            'Content-Type': 'application/json',
            'Authorization': 'Bearer ' + (process.env['API_KEY'] ?? ''),
          },
          
        });
        const data = res.status === 204 ? {} : await res.json().catch(() => ({}));
        if (!res.ok) return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
        return { content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
      } catch (err) {
        return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify({ code: 'FETCH_ERROR', message: String(err) }) }] };
      }
    }

    if (request.params.name === "feature_flags_update") {
      const input = FeatureFlagsUpdateInputSchema.parse(request.params.arguments ?? {});
      let url = "/api/projects/{project_id}/feature_flags/{id}/";
      url = url.replace('{id}', encodeURIComponent(String(input.id)));
      const bodyKeys = new Set(["id"]);
      const bodyPayload = Object.fromEntries(Object.entries(input).filter(([k]) => !bodyKeys.has(k)));
      try {
        const res = await fetch(url, {
          method: "PUT",
          headers: {
            'Content-Type': 'application/json',
            'Authorization': 'Bearer ' + (process.env['API_KEY'] ?? ''),
          },
          body: JSON.stringify(bodyPayload),
        });
        const data = res.status === 204 ? {} : await res.json().catch(() => ({}));
        if (!res.ok) return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
        return { content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
      } catch (err) {
        return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify({ code: 'FETCH_ERROR', message: String(err) }) }] };
      }
    }






































































































































































































































































































































































































































































































































































  return {
    isError: true,
    content: [{ type: 'text' as const, text: `Unknown tool: ${request.params.name}` }],
  };
});

// ── Boot ─────────────────────────────────────────────────────────────────────

async function main() {
  const transport = new StdioServerTransport();
  await server.connect(transport);
  process.stderr.write('posthog-mcp MCP server running on stdio\n');
}

main().catch((err) => {
  process.stderr.write(`Fatal: ${err instanceof Error ? err.message : String(err)}\n`);
  process.exit(1);
});
