// Auto-generated by forge-skill-from-openapi --target=mcp-server --transport=stdio
// API: openai-mcp
// DO NOT EDIT — re-run forge to regenerate

import { Server } from '@modelcontextprotocol/sdk/server/index.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import { CallToolRequestSchema, ListToolsRequestSchema } from '@modelcontextprotocol/sdk/types.js';
import { z } from 'zod';

// ── Zod input schemas (one per operation) ────────────────────────────────────




















export const CreateChatCompletionInputSchema = z.object({
  body: z.record(z.unknown()).optional(),
}).strict();





export const CreateCompletionInputSchema = z.object({
  body: z.record(z.unknown()).optional(),
}).strict();














export const CreateEmbeddingInputSchema = z.object({
  body: z.record(z.unknown()).optional(),
}).strict();













export const ListFilesInputSchema = z.object({
  purpose: z.string().describe("Only return files with the given purpose.").optional(),
  limit: z.number().int().describe("A limit on the number of objects to be returned. Limit can range between 1 and 10,000, and the default is 10,000.\n").optional(),
  order: z.enum(["asc","desc"]).describe("Sort order by the `created_at` timestamp of the objects. `asc` for ascending order and `desc` for descending order.\n").optional(),
  after: z.string().describe("A cursor for use in pagination. `after` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, ending with obj_foo, your subsequent call can include after=obj_foo in order to fetch the next page of the list.\n").optional(),
}).strict();

export const CreateFileInputSchema = z.object({
  body: z.record(z.unknown()).optional(),
}).strict();


export const DeleteFileInputSchema = z.object({
  file_id: z.string().describe("The ID of the file to use for this request."),
}).strict();







export const ListPaginatedFineTuningJobsInputSchema = z.object({
  after: z.string().describe("Identifier for the last job from the previous pagination request.").optional(),
  limit: z.number().int().describe("Number of fine-tuning jobs to retrieve.").optional(),
  metadata: z.record(z.unknown()).describe("Optional metadata filter. To filter, use the syntax `metadata[k]=v`. Alternatively, set `metadata=null` to indicate no metadata.\n").optional(),
}).strict();

export const CreateFineTuningJobInputSchema = z.object({
  body: z.record(z.unknown()).optional(),
}).strict();








export const CreateImageInputSchema = z.object({
  body: z.record(z.unknown()).optional(),
}).strict();


export const ListModelsInputSchema = z.object({}).strict();

export const RetrieveModelInputSchema = z.object({
  model: z.string().describe("The ID of the model to use for this request"),
}).strict();


export const CreateModerationInputSchema = z.object({
  body: z.record(z.unknown()).optional(),
}).strict();







































































































































































// ── Server init ──────────────────────────────────────────────────────────────

const server = new Server(
  { name: "openai-mcp", version: '1.0.0' },
  { capabilities: { tools: {} } },
);

// ── ListTools ─────────────────────────────────────────────────────────────────

server.setRequestHandler(ListToolsRequestSchema, async () => ({
  tools: [
{
    "name": "createChatCompletion",
    "description": "**Starting a new project?** We recommend trying [Responses](/docs/api-reference/responses)\nto take advantage of the latest OpenAI platform features. Compare\n[Chat Completions with Responses](/docs/guides/responses-vs-chat-completions?api-mode=responses).\n\n---\n\nCreates a model response for the given chat conversation. Learn more in the\n[text generation](/docs/guides/text-generation), [vision](/docs/guides/vision),\nand [audio](/docs/guides/audio) guides.\n\nParameter support can differ depending on the model used to generate the\nresponse, particularly for newer reasoning models. Parameters that are only\nsupported for reasoning models are noted below. For the current state of\nunsupported parameters in reasoning models,\n[refer to the reasoning guide](/docs/guides/reasoning).\n\nReturns a chat completion object, or a streamed sequence of chat completion\nchunk objects if the request is streamed.\n",
    "inputSchema": {
      "type": "object",
      "properties": {}
    }
  },
{
    "name": "createCompletion",
    "description": "Creates a completion for the provided prompt and parameters.\n\nReturns a completion object, or a sequence of completion objects if the request is streamed.\n",
    "inputSchema": {
      "type": "object",
      "properties": {}
    }
  },
{
    "name": "createEmbedding",
    "description": "Creates an embedding vector representing the input text.",
    "inputSchema": {
      "type": "object",
      "properties": {}
    }
  },
{
    "name": "listFiles",
    "description": "Returns a list of files.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "purpose": {
          "type": "string",
          "description": "Only return files with the given purpose."
        },
        "limit": {
          "type": "integer",
          "description": "A limit on the number of objects to be returned. Limit can range between 1 and 10,000, and the default is 10,000.\n"
        },
        "order": {
          "type": "string",
          "description": "Sort order by the `created_at` timestamp of the objects. `asc` for ascending order and `desc` for descending order.\n"
        },
        "after": {
          "type": "string",
          "description": "A cursor for use in pagination. `after` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, ending with obj_foo, your subsequent call can include after=obj_foo in order to fetch the next page of the list.\n"
        }
      }
    }
  },
{
    "name": "createFile",
    "description": "Upload a file that can be used across various endpoints. Individual files\ncan be up to 512 MB, and each project can store up to 2.5 TB of files in\ntotal. There is no organization-wide storage limit. Uploads to this\nendpoint are rate-limited to 1,000 requests per minute per authenticated\nuser.\n\n- The Assistants API supports files up to 2 million tokens and of specific\n  file types. See the [Assistants Tools guide](/docs/assistants/tools) for\n  details.\n- The Fine-tuning API only supports `.jsonl` files. The input also has\n  certain required formats for fine-tuning\n  [chat](/docs/api-reference/fine-tuning/chat-input) or\n  [completions](/docs/api-reference/fine-tuning/completions-input) models.\n- The Batch API only supports `.jsonl` files up to 200 MB in size. The input\n  also has a specific required\n  [format](/docs/api-reference/batch/request-input).\n- For Retrieval or `file_search` ingestion, upload files here first. If\n  you need to attach multiple uploaded files to the same vector store, use\n  [`/vector_stores/{vector_store_id}/file_batches`](/docs/api-reference/vector-stores-file-batches/createBatch)\n  instead of attaching them one by one. Vector store attachment has separate\n  limits from file upload, including 2,000 attached files per minute per\n  organization.\n\nPlease [contact us](https://help.openai.com/) if you need to increase these\nstorage limits.\n",
    "inputSchema": {
      "type": "object",
      "properties": {}
    }
  },
{
    "name": "deleteFile",
    "description": "Delete a file and remove it from all vector stores.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "file_id": {
          "type": "string",
          "description": "The ID of the file to use for this request."
        }
      },
      "required": [
        "file_id"
      ]
    }
  },
{
    "name": "listPaginatedFineTuningJobs",
    "description": "List your organization's fine-tuning jobs\n",
    "inputSchema": {
      "type": "object",
      "properties": {
        "after": {
          "type": "string",
          "description": "Identifier for the last job from the previous pagination request."
        },
        "limit": {
          "type": "integer",
          "description": "Number of fine-tuning jobs to retrieve."
        },
        "metadata": {
          "type": "object",
          "description": "Optional metadata filter. To filter, use the syntax `metadata[k]=v`. Alternatively, set `metadata=null` to indicate no metadata.\n"
        }
      }
    }
  },
{
    "name": "createFineTuningJob",
    "description": "Creates a fine-tuning job which begins the process of creating a new model from a given dataset.\n\nResponse includes details of the enqueued job including job status and the name of the fine-tuned models once complete.\n\n[Learn more about fine-tuning](/docs/guides/model-optimization)\n",
    "inputSchema": {
      "type": "object",
      "properties": {}
    }
  },
{
    "name": "createImage",
    "description": "Creates an image given a prompt. [Learn more](/docs/guides/images).\n",
    "inputSchema": {
      "type": "object",
      "properties": {}
    }
  },
{
    "name": "listModels",
    "description": "Lists the currently available models, and provides basic information about each one such as the owner and availability.",
    "inputSchema": {
      "type": "object",
      "properties": {}
    }
  },
{
    "name": "retrieveModel",
    "description": "Retrieves a model instance, providing basic information about the model such as the owner and permissioning.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "model": {
          "type": "string",
          "description": "The ID of the model to use for this request"
        }
      },
      "required": [
        "model"
      ]
    }
  },
{
    "name": "createModeration",
    "description": "Classifies if text and/or image inputs are potentially harmful. Learn\nmore in the [moderation guide](/docs/guides/moderation).\n",
    "inputSchema": {
      "type": "object",
      "properties": {}
    }
  }
  ],
}));

// ── CallTool ──────────────────────────────────────────────────────────────────

server.setRequestHandler(CallToolRequestSchema, async (request) => {



















    if (request.params.name === "createChatCompletion") {
      const input = CreateChatCompletionInputSchema.parse(request.params.arguments ?? {});
      let url = "https://api.openai.com/v1/chat/completions";
      const bodyKeys = new Set([]);
      const bodyPayload = Object.fromEntries(Object.entries(input).filter(([k]) => !bodyKeys.has(k)));
      try {
        const res = await fetch(url, {
          method: "POST",
          headers: {
            'Content-Type': 'application/json',
            'Authorization': 'Bearer ' + (process.env['API_KEY'] ?? ''),
          },
          body: JSON.stringify(bodyPayload),
        });
        const data = res.status === 204 ? {} : await res.json().catch(() => ({}));
        if (!res.ok) return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
        return { content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
      } catch (err) {
        return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify({ code: 'FETCH_ERROR', message: String(err) }) }] };
      }
    }





    if (request.params.name === "createCompletion") {
      const input = CreateCompletionInputSchema.parse(request.params.arguments ?? {});
      let url = "https://api.openai.com/v1/completions";
      const bodyKeys = new Set([]);
      const bodyPayload = Object.fromEntries(Object.entries(input).filter(([k]) => !bodyKeys.has(k)));
      try {
        const res = await fetch(url, {
          method: "POST",
          headers: {
            'Content-Type': 'application/json',
            'Authorization': 'Bearer ' + (process.env['API_KEY'] ?? ''),
          },
          body: JSON.stringify(bodyPayload),
        });
        const data = res.status === 204 ? {} : await res.json().catch(() => ({}));
        if (!res.ok) return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
        return { content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
      } catch (err) {
        return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify({ code: 'FETCH_ERROR', message: String(err) }) }] };
      }
    }














    if (request.params.name === "createEmbedding") {
      const input = CreateEmbeddingInputSchema.parse(request.params.arguments ?? {});
      let url = "https://api.openai.com/v1/embeddings";
      const bodyKeys = new Set([]);
      const bodyPayload = Object.fromEntries(Object.entries(input).filter(([k]) => !bodyKeys.has(k)));
      try {
        const res = await fetch(url, {
          method: "POST",
          headers: {
            'Content-Type': 'application/json',
            'Authorization': 'Bearer ' + (process.env['API_KEY'] ?? ''),
          },
          body: JSON.stringify(bodyPayload),
        });
        const data = res.status === 204 ? {} : await res.json().catch(() => ({}));
        if (!res.ok) return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
        return { content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
      } catch (err) {
        return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify({ code: 'FETCH_ERROR', message: String(err) }) }] };
      }
    }













    if (request.params.name === "listFiles") {
      const input = ListFilesInputSchema.parse(request.params.arguments ?? {});
      let url = "https://api.openai.com/v1/files";
      const qs = new URLSearchParams();
      if (input.purpose !== undefined) qs.set('purpose', String(input.purpose));
      if (input.limit !== undefined) qs.set('limit', String(input.limit));
      if (input.order !== undefined) qs.set('order', String(input.order));
      if (input.after !== undefined) qs.set('after', String(input.after));
      if (qs.toString()) url += '?' + qs.toString();
      try {
        const res = await fetch(url, {
          method: "GET",
          headers: {
            'Content-Type': 'application/json',
            'Authorization': 'Bearer ' + (process.env['API_KEY'] ?? ''),
          },
          
        });
        const data = res.status === 204 ? {} : await res.json().catch(() => ({}));
        if (!res.ok) return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
        return { content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
      } catch (err) {
        return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify({ code: 'FETCH_ERROR', message: String(err) }) }] };
      }
    }

    if (request.params.name === "createFile") {
      const input = CreateFileInputSchema.parse(request.params.arguments ?? {});
      let url = "https://api.openai.com/v1/files";
      const bodyKeys = new Set([]);
      const bodyPayload = Object.fromEntries(Object.entries(input).filter(([k]) => !bodyKeys.has(k)));
      try {
        const res = await fetch(url, {
          method: "POST",
          headers: {
            'Content-Type': 'application/json',
            'Authorization': 'Bearer ' + (process.env['API_KEY'] ?? ''),
          },
          body: JSON.stringify(bodyPayload),
        });
        const data = res.status === 204 ? {} : await res.json().catch(() => ({}));
        if (!res.ok) return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
        return { content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
      } catch (err) {
        return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify({ code: 'FETCH_ERROR', message: String(err) }) }] };
      }
    }


    if (request.params.name === "deleteFile") {
      const input = DeleteFileInputSchema.parse(request.params.arguments ?? {});
      let url = "https://api.openai.com/v1/files/{file_id}";
      url = url.replace('{file_id}', encodeURIComponent(String(input.file_id)));
      try {
        const res = await fetch(url, {
          method: "DELETE",
          headers: {
            'Content-Type': 'application/json',
            'Authorization': 'Bearer ' + (process.env['API_KEY'] ?? ''),
          },
          
        });
        const data = res.status === 204 ? {} : await res.json().catch(() => ({}));
        if (!res.ok) return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
        return { content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
      } catch (err) {
        return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify({ code: 'FETCH_ERROR', message: String(err) }) }] };
      }
    }







    if (request.params.name === "listPaginatedFineTuningJobs") {
      const input = ListPaginatedFineTuningJobsInputSchema.parse(request.params.arguments ?? {});
      let url = "https://api.openai.com/v1/fine_tuning/jobs";
      const qs = new URLSearchParams();
      if (input.after !== undefined) qs.set('after', String(input.after));
      if (input.limit !== undefined) qs.set('limit', String(input.limit));
      if (input.metadata !== undefined) qs.set('metadata', String(input.metadata));
      if (qs.toString()) url += '?' + qs.toString();
      try {
        const res = await fetch(url, {
          method: "GET",
          headers: {
            'Content-Type': 'application/json',
            'Authorization': 'Bearer ' + (process.env['API_KEY'] ?? ''),
          },
          
        });
        const data = res.status === 204 ? {} : await res.json().catch(() => ({}));
        if (!res.ok) return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
        return { content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
      } catch (err) {
        return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify({ code: 'FETCH_ERROR', message: String(err) }) }] };
      }
    }

    if (request.params.name === "createFineTuningJob") {
      const input = CreateFineTuningJobInputSchema.parse(request.params.arguments ?? {});
      let url = "https://api.openai.com/v1/fine_tuning/jobs";
      const bodyKeys = new Set([]);
      const bodyPayload = Object.fromEntries(Object.entries(input).filter(([k]) => !bodyKeys.has(k)));
      try {
        const res = await fetch(url, {
          method: "POST",
          headers: {
            'Content-Type': 'application/json',
            'Authorization': 'Bearer ' + (process.env['API_KEY'] ?? ''),
          },
          body: JSON.stringify(bodyPayload),
        });
        const data = res.status === 204 ? {} : await res.json().catch(() => ({}));
        if (!res.ok) return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
        return { content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
      } catch (err) {
        return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify({ code: 'FETCH_ERROR', message: String(err) }) }] };
      }
    }








    if (request.params.name === "createImage") {
      const input = CreateImageInputSchema.parse(request.params.arguments ?? {});
      let url = "https://api.openai.com/v1/images/generations";
      const bodyKeys = new Set([]);
      const bodyPayload = Object.fromEntries(Object.entries(input).filter(([k]) => !bodyKeys.has(k)));
      try {
        const res = await fetch(url, {
          method: "POST",
          headers: {
            'Content-Type': 'application/json',
            'Authorization': 'Bearer ' + (process.env['API_KEY'] ?? ''),
          },
          body: JSON.stringify(bodyPayload),
        });
        const data = res.status === 204 ? {} : await res.json().catch(() => ({}));
        if (!res.ok) return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
        return { content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
      } catch (err) {
        return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify({ code: 'FETCH_ERROR', message: String(err) }) }] };
      }
    }


    if (request.params.name === "listModels") {
      const input = ListModelsInputSchema.parse(request.params.arguments ?? {});
      let url = "https://api.openai.com/v1/models";
      try {
        const res = await fetch(url, {
          method: "GET",
          headers: {
            'Content-Type': 'application/json',
            'Authorization': 'Bearer ' + (process.env['API_KEY'] ?? ''),
          },
          
        });
        const data = res.status === 204 ? {} : await res.json().catch(() => ({}));
        if (!res.ok) return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
        return { content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
      } catch (err) {
        return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify({ code: 'FETCH_ERROR', message: String(err) }) }] };
      }
    }

    if (request.params.name === "retrieveModel") {
      const input = RetrieveModelInputSchema.parse(request.params.arguments ?? {});
      let url = "https://api.openai.com/v1/models/{model}";
      url = url.replace('{model}', encodeURIComponent(String(input.model)));
      try {
        const res = await fetch(url, {
          method: "GET",
          headers: {
            'Content-Type': 'application/json',
            'Authorization': 'Bearer ' + (process.env['API_KEY'] ?? ''),
          },
          
        });
        const data = res.status === 204 ? {} : await res.json().catch(() => ({}));
        if (!res.ok) return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
        return { content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
      } catch (err) {
        return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify({ code: 'FETCH_ERROR', message: String(err) }) }] };
      }
    }


    if (request.params.name === "createModeration") {
      const input = CreateModerationInputSchema.parse(request.params.arguments ?? {});
      let url = "https://api.openai.com/v1/moderations";
      const bodyKeys = new Set([]);
      const bodyPayload = Object.fromEntries(Object.entries(input).filter(([k]) => !bodyKeys.has(k)));
      try {
        const res = await fetch(url, {
          method: "POST",
          headers: {
            'Content-Type': 'application/json',
            'Authorization': 'Bearer ' + (process.env['API_KEY'] ?? ''),
          },
          body: JSON.stringify(bodyPayload),
        });
        const data = res.status === 204 ? {} : await res.json().catch(() => ({}));
        if (!res.ok) return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
        return { content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }] };
      } catch (err) {
        return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify({ code: 'FETCH_ERROR', message: String(err) }) }] };
      }
    }







































































































































































  return {
    isError: true,
    content: [{ type: 'text' as const, text: `Unknown tool: ${request.params.name}` }],
  };
});

// ── Boot ─────────────────────────────────────────────────────────────────────

async function main() {
  const transport = new StdioServerTransport();
  await server.connect(transport);
  process.stderr.write('openai-mcp MCP server running on stdio\n');
}

main().catch((err) => {
  process.stderr.write(`Fatal: ${err instanceof Error ? err.message : String(err)}\n`);
  process.exit(1);
});
