-- Auto-generated by forge-skill-from-openapi --harden
-- MCP tool call audit log table

CREATE TABLE IF NOT EXISTS mcp_tool_calls (
  id              INTEGER PRIMARY KEY AUTOINCREMENT,
  timestamp       TEXT    NOT NULL DEFAULT (datetime('now')),
  tool_name       TEXT    NOT NULL,
  args_sha256     TEXT    NOT NULL,
  response_status TEXT    NOT NULL CHECK(response_status IN ('success','error','rate_limited','auth_denied')),
  latency_ms      INTEGER NOT NULL,
  user_id         TEXT    NOT NULL,
  server_name     TEXT    NOT NULL,
  error_code      TEXT
);

CREATE INDEX IF NOT EXISTS idx_mcp_tool_calls_timestamp ON mcp_tool_calls(timestamp);
CREATE INDEX IF NOT EXISTS idx_mcp_tool_calls_tool      ON mcp_tool_calls(tool_name, timestamp);
CREATE INDEX IF NOT EXISTS idx_mcp_tool_calls_user      ON mcp_tool_calls(user_id, timestamp);
